// Package servicetest exposes non-browser runtime seams for acceptance tests.
// Browser-conversation tests import the public browserconversation contract.
package servicetest

import (
	sessioncontract "github.com/portpowered/go-agent-harness/agent-cli/internal/services/agentsession"
	serviceDevices "github.com/portpowered/go-agent-harness/agent-cli/internal/services/devices"
	impl "github.com/portpowered/go-agent-harness/agent-cli/internal/services/internal/agentruntime"
	runtimeRooms "github.com/portpowered/go-agent-harness/go-agent-runtime/services/rooms"
	runtimeSession "github.com/portpowered/go-agent-harness/go-agent-runtime/services/session"
)

const DefaultOpenAIRealtimeModel = impl.DefaultOpenAIRealtimeModel

var ErrInvalidOpenAIRealtimeVoice = sessioncontract.ErrInvalidOpenAIRealtimeVoice
var ErrRTCSessionMediaUnavailable = impl.ErrRTCSessionMediaUnavailable
var ErrRoomLaunchPathConflict = runtimeRooms.ErrLaunchPathConflict
var ErrRoomReplayBundleIncomplete = impl.ErrRoomReplayBundleIncomplete
var ErrRoomReplaySourceConflict = impl.ErrRoomReplaySourceConflict
var ErrSessionAudioInputConflict = serviceDevices.ErrSessionAudioInputConflict
var ErrSessionAudioOutputConflict = serviceDevices.ErrSessionAudioOutputConflict
var ErrSessionAudioInTurnBargeRequiresSequence = impl.ErrSessionAudioInTurnBargeRequiresSequence
var ErrSessionAudioResponseIncomplete = impl.ErrSessionAudioResponseIncomplete
var ErrSessionImageContinuationIncomplete = impl.ErrSessionImageContinuationIncomplete
var ErrSessionScheduledAudioIncomplete = runtimeSession.ErrLiveScheduledAudioIncomplete
var ErrSessionUnresolvedToolResults = sessioncontract.ErrSessionUnresolvedToolResults
var NewOpenAIRealtimeSessionInferencerWithOptions = impl.NewOpenAIRealtimeSessionInferencerWithOptions
var NewOpenAIRealtimeSessionInferencerWithToolsAndOptions = impl.NewOpenAIRealtimeSessionInferencerWithToolsAndOptions
var NewGrokSessionInferencer = impl.NewGrokSessionInferencer
var NewGrokSessionInferencerWithOptions = impl.NewGrokSessionInferencerWithOptions
var PrepareRTCDeviceBindings = impl.PrepareRTCDeviceBindings
var ValidateSessionAudioDeviceConflicts = serviceDevices.ValidateSessionAudioDeviceConflicts
var RunSession = impl.RunSession
var RunSessionWithInstructions = impl.RunSessionWithInstructions
var RunSessionWithMaxDuration = impl.RunSessionWithMaxDuration
var RunSessionWithMaxDurationClock = impl.RunSessionWithMaxDurationClock

const ParticipantTerminationEnded = impl.ParticipantTerminationEnded
const ParticipantTerminationError = impl.ParticipantTerminationError

type InvalidOpenAIRealtimeVoiceError = sessioncontract.InvalidOpenAIRealtimeVoiceError
type RTCMediaEndpoints = impl.RTCMediaEndpoints
type RTCMediaSession = impl.RTCMediaSession
type RTCDeviceBindingRequest = impl.RTCDeviceBindingRequest
type RTCDeviceBindingError = impl.RTCDeviceBindingError
type ScheduledAudioInput = impl.ScheduledAudioInput
type SelfPlayRunOptions = impl.SelfPlayRunOptions
type SessionAudioInTurnBargeError = impl.SessionAudioInTurnBargeError
type SessionAudioInput = impl.SessionAudioInput
type SessionTextSeed = impl.SessionTextSeed
type SessionDiagnosticRecord = impl.SessionDiagnosticRecord
type SessionDurationTimer = impl.SessionDurationTimer
type SessionImageContinuationError = impl.SessionImageContinuationError
type SessionRTCComponents = impl.SessionRTCComponents
type SessionRTCDataPlane = impl.SessionRTCDataPlane
type SessionRunOptions = impl.SessionRunOptions
type SessionRuntimeSelection = impl.SessionRuntimeSelection
type SessionScheduledAudioIncompleteError = runtimeSession.LiveScheduledAudioIncompleteError
type SessionToolContinuationError = impl.SessionToolContinuationError
type SessionToolDiagnostic = impl.SessionToolDiagnostic
type SessionUnresolvedToolResultsError = sessioncontract.SessionUnresolvedToolResultsError

const SessionMaxDurationReason = impl.SessionMaxDurationReason
const SessionSilentProviderTimeoutClassification = impl.SessionSilentProviderTimeoutClassification
const SessionTransportWebRTC = impl.SessionTransportWebRTC
const SessionDiagnosticEventFailure = impl.SessionDiagnosticEventFailure
const SessionDiagnosticEventMetrics = impl.SessionDiagnosticEventMetrics
const SessionDiagnosticEventToolCall = impl.SessionDiagnosticEventToolCall
const SessionDiagnosticEventTurn = impl.SessionDiagnosticEventTurn
const SessionDiagnosticFieldPendingToolContinuationCount = impl.SessionDiagnosticFieldPendingToolContinuationCount
const SessionDiagnosticFieldPendingToolContinuationIDs = impl.SessionDiagnosticFieldPendingToolContinuationIDs
const SessionDiagnosticFieldUnresolvedToolCallIDs = impl.SessionDiagnosticFieldUnresolvedToolCallIDs
const SessionDiagnosticFieldUnresolvedToolResultCount = impl.SessionDiagnosticFieldUnresolvedToolResultCount
