// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/roomreplay"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/rooms"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/rooms/internal/lifecycle"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/rooms/internal/planning"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/rooms/internal/service"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/session"
	"github.com/portpowered/go-agent-harness/go-audio/pkg/clock"
)

// Injectors from providers.go:

func NewService(dependencies Dependencies) rooms.Service {
	planner := newPlanner()
	runner := newRunner(dependencies)
	serviceDependencies := newServiceDependencies(planner, runner, dependencies)
	roomsService := service.New(serviceDependencies)
	return roomsService
}

// providers.go:

type Dependencies struct {
	Live     session.LiveService
	Media    rooms.MediaFactory
	Replay   roomreplay.Service
	Clock    clock.Scheduler
	Evidence rooms.EvidenceService
	Latency  rooms.LatencyService
}

func newPlanner() planning.Planner { return planning.New() }

func newRunner(dependencies Dependencies) lifecycle.Runner {
	return lifecycle.New(lifecycle.Dependencies{
		Live: dependencies.Live, Media: dependencies.Media, Clock: dependencies.Clock,
		Evidence: dependencies.Evidence, Latency: dependencies.Latency,
	})
}

func newServiceDependencies(planner planning.Planner, runner lifecycle.Runner, dependencies Dependencies) service.Dependencies {
	return service.Dependencies{Planner: planner, Replay: dependencies.Replay, Runner: runner, Evidence: dependencies.Evidence}
}
