// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-loop/pkg/messages"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/rooms"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/rooms/internal/evidence"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/rooms/internal/lifecycle"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/rooms/internal/planning"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/rooms/internal/service"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/session"
	"github.com/portpowered/go-agent-harness/go-audio/pkg/clock"
)

// Injectors from participant_lifecycle.go:

// NewParticipantLifecycle is the dedicated Wire entry point for the
// invocation-scoped participant state machine.
func NewParticipantLifecycle(options rooms.ParticipantLifecycleOptions) rooms.ParticipantLifecycle {
	participantLifecycle := lifecycle.NewParticipantLifecycle(options)
	return participantLifecycle
}

// NewTrackedSession is the dedicated Wire entry point for session ownership
// and selective post-bound admission.
func NewTrackedSession(session messages.Session, participant rooms.ParticipantLifecycle, admissionClosed <-chan struct{}) rooms.TrackedSession {
	trackedSession := lifecycle.NewTrackedSession(session, participant, admissionClosed)
	return trackedSession
}

// NewConnectionTracker is the dedicated Wire entry point for the first
// connection outcome and transport cleanup boundary.
func NewConnectionTracker(inner messages.SessionInferencer, participant rooms.ParticipantLifecycle, admissionClosed <-chan struct{}) rooms.ParticipantConnectionTracker {
	participantConnectionTracker := lifecycle.NewConnectionTracker(inner, participant, admissionClosed)
	return participantConnectionTracker
}

// Injectors from providers.go:

func NewService(dependencies Dependencies) rooms.Service {
	planner := newPlanner()
	loader := newEvidence()
	runner := newRunner(dependencies)
	serviceDependencies := newServiceDependencies(planner, loader, runner)
	roomsService := service.New(serviceDependencies)
	return roomsService
}

// providers.go:

type Dependencies struct {
	Live  session.LiveService
	Media rooms.MediaFactory
	Clock clock.Scheduler
}

func newPlanner() planning.Planner { return planning.New() }

func newEvidence() evidence.Loader { return evidence.New() }

func newRunner(dependencies Dependencies) lifecycle.Runner {
	return lifecycle.New(lifecycle.Dependencies{
		Live: dependencies.Live, Media: dependencies.Media, Clock: dependencies.Clock,
	})
}

func newServiceDependencies(planner planning.Planner, evidenceLoader evidence.Loader, runner lifecycle.Runner) service.Dependencies {
	return service.Dependencies{Planner: planner, Evidence: evidenceLoader, Runner: runner}
}
