#!/usr/bin/env python3
"""Verify C136 recovery ownership, retirement, and mutation controls."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess
import sys


HERE = Path(__file__).resolve().parent
ROOT = next(parent for parent in HERE.parents if (parent / "go.work").is_file())
BRANCH = "codex/audio-runtime-c136-recover-c87-session-turns"
BASE = "bd6a1289218d1bef1a3af36e64e9d4496062416f"
ADAPTER = "agent-cli/internal/services/internal/agentruntime/session_turns.go"
ADAPTER_TEST = "agent-cli/internal/services/internal/agentruntime/session_turns_test.go"
RUNTIME = "go-agent-runtime/services/sessionturns"
EVIDENCE = "docs/temp/projects/audio-runtime/audio-runtime-c136-recover-c87-session-turns"
C87_EVIDENCE = "docs/temp/projects/audio-runtime/audio-runtime-c87-retire-cli-session-turns"
C150_EVIDENCE = "docs/temp/projects/audio-runtime/audio-runtime-c150-recover-c136-c87-session-turns"
C166_EVIDENCE = "docs/temp/projects/audio-runtime/audio-runtime-c166-recover-c150-session-turns-handoff"
SHARED_EXCLUSIONS = {
    "scripts/wire-packages.txt",
    "docs/architecture/architecture-size-baseline.json",
    "docs/architecture/architecture-policy.json",
}
WIRE_REGISTRY = "scripts/wire-packages.txt"
ARCHITECTURE_POLICY = "docs/architecture/architecture-policy.json"
SESSION_TURNS_BASELINE = "docs/architecture/baselines/github.com/portpowered/go-agent-harness/agent-cli/internal/services/internal/agentruntime/session_turns.go.json"
SESSION_TURNS_TEST_BASELINE = "docs/architecture/baselines/github.com/portpowered/go-agent-harness/agent-cli/internal/services/internal/agentruntime/session_turns_test.go.json"
SESSION_TURNS_WIRE = "go-agent-runtime/services/sessionturns/wire"
SESSION_TURNS_GENERATED_FILE = {
    "module": "go-agent-runtime",
    "pattern": "services/sessionturns/wire/wire_gen.go",
    "generator": "wire",
    "header": "// Code generated by Wire. DO NOT EDIT.",
}
C166_SHARED_PATHS = {
    WIRE_REGISTRY,
    ARCHITECTURE_POLICY,
    SESSION_TURNS_BASELINE,
    SESSION_TURNS_TEST_BASELINE,
}
BASELINE_KEY_FIELDS = ("rule", "module", "package", "file", "symbol")
STALE_SESSION_TURNS_KEYS = {
    ("mutable-global", "github.com/portpowered/go-agent-harness/agent-cli", "github.com/portpowered/go-agent-harness/agent-cli/internal/services/internal/agentruntime", "internal/services/internal/agentruntime/session_turns.go", symbol)
    for symbol in (
        "ErrEmptyTurn",
        "ErrInvalidTurnDirection",
        "ErrInvalidTurnTick",
        "ErrMissingTurnInferencer",
        "ErrSessionClosed",
        "ErrSessionEndedWithActiveTurn",
        "ErrTurnAlreadyActive",
        "ErrTurnEndWithoutStart",
        "ErrTurnMismatch",
    )
}
STALE_SESSION_TURNS_KEYS.add(
    (
        "cognitive-complexity",
        "github.com/portpowered/go-agent-harness/agent-cli",
        "github.com/portpowered/go-agent-harness/agent-cli/internal/services/internal/agentruntime",
        "internal/services/internal/agentruntime/session_turns.go",
        "readTurnResponse",
    )
)
STALE_SESSION_TURNS_TEST_KEYS = {
    (
        "cyclomatic-complexity",
        "github.com/portpowered/go-agent-harness/agent-cli",
        "github.com/portpowered/go-agent-harness/agent-cli/internal/services/internal/agentruntime",
        "internal/services/internal/agentruntime/session_turns_test.go",
        "TestSessionTurns_FiveTurnsUseOnePersistentSessionAndExactLifecycle",
    ),
    (
        "mutable-global",
        "github.com/portpowered/go-agent-harness/agent-cli",
        "github.com/portpowered/go-agent-harness/agent-cli/internal/services/internal/agentruntime",
        "internal/services/internal/agentruntime/session_turns_test.go",
        "noTurnSetup",
    ),
}


class VerificationError(RuntimeError):
    pass


def require(condition: bool, message: str) -> None:
    if not condition:
        raise VerificationError(message)


def git(*args: str, check: bool = True) -> str:
    result = subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True, check=False, timeout=30)
    if check:
        require(result.returncode == 0, result.stderr.strip() or f"git {' '.join(args)} failed")
    return result.stdout.strip()


def changed_paths() -> set[str]:
    paths = set(git("diff", "--name-only", "origin/main...HEAD").splitlines())
    paths.update(git("diff", "--name-only").splitlines())
    paths.update(git("diff", "--cached", "--name-only").splitlines())
    paths.update(git("ls-files", "--others", "--exclude-standard").splitlines())
    return {path for path in paths if path}


def run_test(cwd: Path, package: str, pattern: str) -> None:
    environment = {**__import__("os").environ, "GOWORK": "off"}
    result = subprocess.run(
        ["go", "test", package, "-run", pattern, "-count=1"],
        cwd=cwd,
        env=environment,
        capture_output=True,
        text=True,
        timeout=60,
        check=False,
    )
    require(result.returncode == 0, result.stdout + result.stderr)


def check_scope() -> None:
    paths = changed_paths()
    for path in paths:
        allowed = path == ADAPTER or path == ADAPTER_TEST or path.startswith(RUNTIME + "/") or path.startswith("coverage-manifest/go-agent-runtime/services/sessionturns/") or path.startswith(EVIDENCE + "/") or path.startswith(C87_EVIDENCE + "/") or path.startswith(C150_EVIDENCE + "/") or path.startswith(C166_EVIDENCE + "/") or path in C166_SHARED_PATHS
        require(allowed, f"unowned changed path: {path}")
    require(not (paths & (SHARED_EXCLUSIONS - C166_SHARED_PATHS)), "shared registry or architecture baseline changed outside the C166 lease")


def baseline_key(entry: dict[str, object]) -> tuple[object, ...]:
    return tuple(entry.get(field) for field in BASELINE_KEY_FIELDS)


def check_shared_repairs() -> dict[str, object]:
    registry_before = git("show", f"origin/main:{WIRE_REGISTRY}").splitlines()
    registry_after = (ROOT / WIRE_REGISTRY).read_text(encoding="utf-8").splitlines()
    require(registry_after.count(SESSION_TURNS_WIRE) == 1, "sessionturns Wire registry entry is missing or duplicated")
    require([line for line in registry_after if line != SESSION_TURNS_WIRE] == registry_before, "Wire registry changed outside the C166 entry")

    policy_before = json.loads(git("show", f"origin/main:{ARCHITECTURE_POLICY}"))
    policy_after = json.loads((ROOT / ARCHITECTURE_POLICY).read_text(encoding="utf-8"))
    require(policy_after.get("generated_files", []).count(SESSION_TURNS_GENERATED_FILE) == 1, "sessionturns generated-file policy entry is missing or duplicated")
    policy_without_sessionturns = dict(policy_after)
    policy_without_sessionturns["generated_files"] = [
        entry for entry in policy_after.get("generated_files", []) if entry != SESSION_TURNS_GENERATED_FILE
    ]
    require(policy_without_sessionturns == policy_before, "architecture policy changed outside the C166 entry")

    baseline_specs = (
        (SESSION_TURNS_BASELINE, STALE_SESSION_TURNS_KEYS),
        (SESSION_TURNS_TEST_BASELINE, STALE_SESSION_TURNS_TEST_KEYS),
    )
    for path, stale_keys in baseline_specs:
        before = json.loads(git("show", f"origin/main:{path}"))
        after = json.loads((ROOT / path).read_text(encoding="utf-8"))
        expected_entries = [entry for entry in before["entries"] if baseline_key(entry) not in stale_keys]
        require(after.get("entries") == expected_entries, f"baseline changed outside the demonstrated C166 deletions: {path}")
        before_without_stale = dict(before)
        before_without_stale["entries"] = expected_entries
        require(after == before_without_stale, f"baseline metadata changed outside the demonstrated C166 deletions: {path}")
    return {"wire_registry": True, "generated_file_policy": True, "stale_baselines_deleted": 12}


def check_retirement() -> dict[str, object]:
    adapter_lines = len((ROOT / ADAPTER).read_text(encoding="utf-8").splitlines())
    baseline = git("show", f"{BASE}:{ADAPTER}")
    require(len(baseline.splitlines()) == 243, "planning-main session_turns.go is not the 243-line baseline")
    require(adapter_lines <= 45, f"CLI adapter has {adapter_lines} lines; maximum is 45")
    adapter = (ROOT / ADAPTER).read_text(encoding="utf-8")
    require("Deprecated:" in adapter and "wire.NewService" in adapter, "CLI file is not an explicit deprecated Wire delegation")
    require("sync" not in adapter and "messages" not in adapter, "CLI adapter retains state or protocol implementation")
    return {"baseline_lines": 243, "adapter_lines": adapter_lines}


def check_contract() -> dict[str, object]:
    public_files = [path for path in (ROOT / RUNTIME).glob("*.go") if not path.name.endswith("_test.go")]
    public_text = "\n".join(path.read_text(encoding="utf-8") for path in public_files)
    require("type Service interface" in public_text and "type SessionTurns struct" not in public_text, "public package exposes implementation state")
    require("internal/service" not in public_text, "public contract imports private implementation")
    wire = (ROOT / RUNTIME / "wire").read_text(encoding="utf-8") if (ROOT / RUNTIME / "wire").is_file() else ""
    wire_gen = ROOT / RUNTIME / "wire" / "wire_gen.go"
    require(wire_gen.is_file(), "dedicated generated Wire constructor is missing")
    require("wireinject" in (ROOT / RUNTIME / "wire" / "wire.go").read_text(encoding="utf-8"), "Wire injector source is missing its build tag")
    require("NewService" in wire_gen.read_text(encoding="utf-8") and "sessionturns.Service" in wire_gen.read_text(encoding="utf-8"), "Wire does not return the public service")
    return {"public_contract": True, "generated_wire": True}


def check_mutations() -> dict[str, object]:
    service = (ROOT / RUNTIME / "internal" / "service" / "service.go").read_text(encoding="utf-8")
    protocol = (ROOT / RUNTIME / "internal" / "service" / "protocol.go").read_text(encoding="utf-8")
    tests = (ROOT / RUNTIME / "internal" / "service" / "service_test.go").read_text(encoding="utf-8")
    require("tick <= active.StartTick" in service and "tick <= s.history" in service, "monotonic tick guards are missing")
    require("IsNonTerminal" in protocol and "StreamTypeMessageEnd" in protocol, "terminal response guard is missing")
    require("InvalidTransitionsPreserveState" in tests and "NonTerminalResponseIsSkipped" in tests and "TerminalResponsePreservesIdentity" in tests, "mutation regression tests are missing")
    run_test(ROOT / "go-agent-runtime", "./services/sessionturns/internal/service", "TestService(InvalidTransitionsPreserveState|NonTerminalResponseIsSkipped|TerminalResponsePreservesIdentity|ResponseCancellationClearsActive|DeepCopiesResponseBytes)")
    return {"monotonic_tick_guard": True, "terminal_boundary_guard": True, "regression_tests": True}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=["mutations", "retirement-and-adapter", "owned-and-excluded-paths"], required=True)
    args = parser.parse_args()
    check_scope()
    checks: dict[str, object] = {}
    checks["shared_repairs"] = check_shared_repairs()
    if args.mode in {"retirement-and-adapter", "owned-and-excluded-paths"}:
        checks["retirement"] = check_retirement()
    if args.mode == "retirement-and-adapter":
        checks["contract"] = check_contract()
        run_test(ROOT / "agent-cli", "./internal/services/internal/agentruntime", "TestDeprecatedSessionTurns")
        run_test(HERE / "external-consumer", "./...", "TestExternalConsumerUsesPublicSessionTurnsContract")
    if args.mode == "mutations":
        checks["mutations"] = check_mutations()
    print(json.dumps({"schema": "audio-runtime.c136.verification/v1", "mode": args.mode, "passed": True, "branch": git("branch", "--show-current"), "head": git("rev-parse", "HEAD"), "checks": checks}, sort_keys=True))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (VerificationError, OSError, subprocess.SubprocessError) as error:
        print(f"verification failure: {error}", file=sys.stderr)
        raise SystemExit(1)
