// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/providers"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/providers/internal/terminalpolicy"
)

// Injectors from terminal_policy.go:

// NewTerminalPolicy is the dedicated Wire injector for the provider terminal
// policy. The extra generation tag keeps this independent graph out of the
// existing full provider graph's generated file.
func NewTerminalPolicy() providers.TerminalPolicy {
	policy := terminalpolicy.New()
	return policy
}
