// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/providers"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/providers/internal/admission"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/providers/internal/catalog"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/providers/internal/service"
)

// Injectors from providers.go:

// NewService assembles the provider service from explicit host ports.
func NewService(deps Dependencies) providers.FullService {
	client := deps.HTTPClient
	logger := deps.Logger
	timerSource := deps.Clock
	recordingService := deps.Recording
	modelCatalog := NewModelCatalog()
	providerCaptureService := deps.ProviderCapture
	serviceService := service.New(client, logger, timerSource, recordingService, modelCatalog, providerCaptureService)
	return serviceService
}

// providers.go:

// NewModelCatalog installs the provider-owned immutable model catalog at the
// application composition boundary.
func NewModelCatalog() providers.ModelCatalog { return catalog.New() }

// NewModelAdmission constructs the provider-owned admission role around an
// explicitly supplied catalog. This keeps custom catalogs usable by an
// independent consumer without exposing providers/internal packages.
func NewModelAdmission(modelCatalog providers.ModelCatalog) providers.ModelAdmission {
	return admission.NewService(modelCatalog)
}
