// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/audiorate"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/audiorate/internal/service"
)

// Injectors from providers.go:

// NewService assembles the private audio-rate implementation and returns only
// the public service contract.
func NewService() audiorate.Service {
	serviceService := service.New()
	return serviceService
}
