// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/audiocodec"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/audiocodec/internal/service"
)

// Injectors from wire.go:

// NewService constructs one independent codec service. It performs no process
// lookup or filesystem access until Convert is called.
func NewService() audiocodec.Service {
	serviceService := service.New()
	return serviceService
}
