// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/retrypolicy"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/retrypolicy/internal/service"
)

// Injectors from wire.go:

// NewService returns a fresh stateless retry-policy service.
func NewService() retrypolicy.Service {
	serviceService := service.New()
	return serviceService
}
