// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionupdate"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionupdate/internal/service"
)

// Injectors from providers.go:

// NewService assembles the session-update service.
func NewService() sessionupdate.Service {
	serviceService := service.New()
	return serviceService
}
