#!/usr/bin/env python3
"""Verify the C85 scheduler retirement and ownership boundary."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import subprocess


ROOT = Path(__file__).resolve().parents[5]
BASELINE = "84c91ee1b41d9ff0ba7e31f321c61f6e34c7a72f"
BRANCH = "codex/audio-runtime-c85-retire-cli-room-replay-scheduler"
SCHEDULER = "agent-cli/internal/services/internal/agentruntime/session_room_replay_scheduler.go"
TEST = "agent-cli/internal/services/internal/agentruntime/session_room_replay_scheduler_test.go"
ORCHESTRATION = "agent-cli/internal/services/internal/agentruntime/session_room_orchestration.go"
EVIDENCE_PREFIX = "docs/temp/projects/audio-runtime/audio-runtime-c85-retire-cli-room-replay-scheduler/"
OWNED_EXACT = {SCHEDULER, TEST, ORCHESTRATION}
OWNED_PREFIXES = (
    "go-agent-runtime/services/roomreplayschedule/",
    "coverage-manifest/go-agent-runtime/services/roomreplayschedule/",
    EVIDENCE_PREFIX,
)
EXCLUDED = {
    "scripts/wire-packages.txt",
    "docs/architecture/architecture-size-baseline.json",
    "agent-cli/internal/services/internal/agentruntime/session_room_replay_bundle.go",
    "agent-cli/internal/services/internal/agentruntime/session_room_lifecycle.go",
    "agent-cli/internal/services/internal/agentruntime/session_room_run.go",
}


def git(*args: str) -> str:
    return subprocess.run(["git", *args], cwd=ROOT, check=True, capture_output=True, text=True).stdout


def require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def source(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def verify_retirement() -> dict[str, object]:
    baseline = git("show", f"{BASELINE}:{SCHEDULER}")
    current = source(SCHEDULER)
    baseline_lines = len(baseline.splitlines())
    current_lines = len(current.splitlines())
    require(baseline_lines == 409, f"origin/main scheduler baseline is {baseline_lines}, want 409")
    require(current_lines <= 159, f"retained scheduler is {current_lines} lines, want at most 159")
    require(baseline_lines - current_lines >= 250, "scheduler retirement is less than 250 lines")
    for marker in (
        "roomReplayScheduledFrame",
        "roomReplayContribution",
        "roomReplaySpeechSegment",
        "normalizeRoomReplayPCM",
        "LoadSessionCapture",
        "ConvertPCM16Bytes",
        "sort.Slice",
    ):
        require(marker not in current, f"CLI retained scheduler decision {marker}")
    public = source("go-agent-runtime/services/roomreplayschedule/contract.go")
    private = source("go-agent-runtime/services/roomreplayschedule/internal/service/build.go")
    wire = source("go-agent-runtime/services/roomreplayschedule/wire/wire.go")
    generated = source("go-agent-runtime/services/roomreplayschedule/wire/wire_gen.go")
    require("agent-cli" not in public and "agent-cli" not in private, "runtime scheduler imports CLI")
    require("func init" not in public + private + wire, "scheduler has hidden initialization")
    require("wire.Build" in wire and "service.New" in wire, "dedicated Wire constructor is missing")
    require("Code generated by Wire" in generated, "generated Wire constructor is missing")
    return {"baseline_lines": baseline_lines, "current_lines": current_lines, "retired_lines": baseline_lines - current_lines}


def verify_scope() -> dict[str, object]:
    require(git("branch", "--show-current").strip() == BRANCH, "candidate branch does not match the admitted branch")
    changed = [path for path in git("diff", f"{BASELINE}...HEAD", "--name-only").splitlines() if path]
    require(changed, "candidate diff is empty")
    require(
        all(path in OWNED_EXACT or path.startswith(OWNED_PREFIXES) for path in changed),
        f"candidate changed an unowned path: {changed}",
    )
    forbidden = sorted(set(changed) & EXCLUDED)
    require(not forbidden, f"excluded path changed: {forbidden}")
    external = source(EVIDENCE_PREFIX + "external-consumer/main.go")
    imports = set(re.findall(r'"(github\.com/portpowered/go-agent-harness/[^\"]+)"', external))
    require(
        imports == {
            "github.com/portpowered/go-agent-harness/go-agent-runtime/services/roomreplayschedule",
            "github.com/portpowered/go-agent-harness/go-agent-runtime/services/roomreplayschedule/wire",
        },
        f"external consumer imports outside the public scheduler boundary: {sorted(imports)}",
    )
    return {"changed_paths": changed, "excluded_paths_changed": forbidden, "external_imports": sorted(imports)}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=("retirement-and-adapter", "owned-and-excluded-paths", "all"), default="all")
    args = parser.parse_args()
    report: dict[str, object] = {"schema": "audio-runtime.c85.scheduler-verification.v1", "baseline": BASELINE}
    if args.mode in ("retirement-and-adapter", "all"):
        report["retirement"] = verify_retirement()
    if args.mode in ("owned-and-excluded-paths", "all"):
        report["scope"] = verify_scope()
    report["passed"] = True
    print(json.dumps(report, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
