// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	devices2 "github.com/portpowered/go-agent-harness/go-agent-runtime/services/devices"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/devices/internal/file"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/devices/internal/media"
	"github.com/portpowered/go-agent-harness/go-audio/pkg/mixer"
	"github.com/portpowered/go-agent-harness/go-device-gateway/pkg/devices"
)

// Injectors from providers.go:

// NewService creates the process-scoped device service. It is inert until a
// caller invokes Open with a normalized request.
func NewService(registry devices.DeviceRegistry) devices2.Service {
	factory := newFactory(registry)
	return factory
}

// NewFileService assembles the finite file-backed device role. The returned
// service is stateless; each Open call takes ownership of its caller-opened
// source and sink only after successful admission.
func NewFileService() devices2.Service {
	factory := newFileFactory()
	return factory
}

// providers.go:

func newFactory(registry devices.DeviceRegistry) *media.Factory {
	return media.NewFactory(registry, mixer.DefaultFormat())
}

func newFileFactory() *file.Factory { return file.NewFactory() }
