// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/roomterminal"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/roomterminal/internal/service"
)

// NewService creates a stateless room terminal policy service.
func NewService() roomterminal.Service {
	serviceService := service.New()
	return serviceService
}
