// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessiondiagnostics"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessiondiagnostics/internal/service"
)

// Injectors from providers.go:

// NewService constructs one response lifecycle reducer.
func NewService(options sessiondiagnostics.Options) sessiondiagnostics.Service {
	sessiondiagnosticsService := service.New(options)
	return sessiondiagnosticsService
}
