// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/providers"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionconfig"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionconfig/internal/service"
)

// Injectors from providers.go:

// NewService assembles the public session configuration contract.
func NewService(deps Dependencies) sessionconfig.Service {
	modelCatalog := deps.ModelCatalog
	serviceService := service.New(modelCatalog)
	return serviceService
}

// providers.go:

// Dependencies supplies the immutable provider model catalog used for model
// capability admission. Hosts may inject a custom catalog for deterministic
// tests and independent consumers.
type Dependencies struct {
	ModelCatalog providers.ModelCatalog
}
