// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionroomerrors"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionroomerrors/internal/service"
)

// NewService constructs an independent room-error service.
func NewService() sessionroomerrors.Service {
	serviceService := service.New()
	return serviceService
}
