// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/imageinput"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/imageinput/internal/service"
)

// Injectors from providers.go:

// NewService assembles image preparation and publication from the host-owned
// content loader. No filesystem or provider configuration is discovered here.
func NewService(loader imageinput.ContentLoader) imageinput.Service {
	serviceService := service.New(loader)
	return serviceService
}
