// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/toolpublication"
)

// Injectors from wire.go:

// NewService constructs the reusable publication service.
func NewService(dependencies Dependencies) toolpublication.Service {
	service := newService(dependencies)
	return service
}
