// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionfailure"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionfailure/internal/service"
)

// Injectors from providers.go:

// NewService assembles one invocation-local failure service.
func NewService(dependencies sessionfailure.Dependencies) sessionfailure.Service {
	serviceService := service.New(dependencies)
	return serviceService
}
