// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionlive"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionlive/internal/service"
)

// Injectors from wire.go:

// NewService returns a fresh stateless service graph. Invocation state is
// supplied to Run, so separate calls cannot share timers, loops, or buffers.
func NewService() sessionlive.Service {
	serviceService := service.New()
	return serviceService
}
