// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/audioinput"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/audioinput/internal/stream"
	"github.com/portpowered/go-agent-harness/go-audio/pkg/clock"
)

// Injectors from providers.go:

// NewService creates an inert service. The caller supplies the clock used by
// paced sources when a request does not provide a per-input clock.
func NewService(source clock.Source) audioinput.Service {
	service := stream.New(source)
	return service
}
