// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/audioinput"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/audioinput/internal/stream"
	"github.com/portpowered/go-agent-harness/go-audio/pkg/clock"
)

// Injectors from providers.go:

func NewService(source clock.Source) audioinput.Service {
	streamService := stream.New(source)
	return streamService
}
