package policy

import "github.com/portpowered/go-agent-harness/go-agent-runtime/services/browserconversation"

type BrowserConversationScenario = browserconversation.BrowserConversationScenario
type BrowserScenario = browserconversation.BrowserScenario
type WebMCPScenario = browserconversation.WebMCPScenario
type WebMCPConversationScenario = browserconversation.WebMCPConversationScenario
type BrowserConversationScenarioError = browserconversation.BrowserConversationScenarioError
type BrowserConversationFixture = browserconversation.BrowserConversationFixture
type BrowserConversationPage = browserconversation.BrowserConversationPage
type BrowserConversationStep = browserconversation.BrowserConversationStep
type ScheduledAudioInput = browserconversation.ScheduledAudioInput
type BrowserStateTransition = browserconversation.BrowserStateTransition
type BrowserCustomerNavigation = browserconversation.BrowserCustomerNavigation
type BrowserConversationCorrection = browserconversation.BrowserConversationCorrection
type BrowserConversationInterruptTrigger = browserconversation.BrowserConversationInterruptTrigger
type BrowserConversationInterrupt = browserconversation.BrowserConversationInterrupt
type BrowserConversationCancelRequest = browserconversation.BrowserConversationCancelRequest
type BrowserConversationTabStateRequired = browserconversation.BrowserConversationTabStateRequired
type BrowserConversationScenarioValue = browserconversation.BrowserConversationScenarioValue
type BrowserConversationScenarioForSession = browserconversation.BrowserConversationScenarioForSession
type BrowserConversationValidator = browserconversation.BrowserConversationValidator
type BrowserConversationValidatorFunc = browserconversation.BrowserConversationValidatorFunc
type BrowserConversationTurn = browserconversation.BrowserConversationTurn
type BrowserConversationInvocationObservation = browserconversation.BrowserConversationInvocationObservation
type BrowserConversationBrokerCall = browserconversation.BrowserConversationBrokerCall
type BrowserConversationInputJSONAttempt = browserconversation.BrowserConversationInputJSONAttempt
type BrowserConversationInputJSONValidity = browserconversation.BrowserConversationInputJSONValidity
type BrowserConversationRecoveryEvidence = browserconversation.BrowserConversationRecoveryEvidence
type BrowserConversationCorrectionEvidence = browserconversation.BrowserConversationCorrectionEvidence
type BrowserConversationOracleSnapshot = browserconversation.BrowserConversationOracleSnapshot
type BrowserConversationMechanicalEvaluation = browserconversation.BrowserConversationMechanicalEvaluation
type BrowserConversationResult = browserconversation.BrowserConversationResult
type BrowserConversationLifecycleEvidence = browserconversation.BrowserConversationLifecycleEvidence
type BrowserConversationCancellationEvidence = browserconversation.BrowserConversationCancellationEvidence
type BrowserConversationValidatorVerdict = browserconversation.BrowserConversationValidatorVerdict
type BrowserConversationValidatorCheck = browserconversation.BrowserConversationValidatorCheck
type BrowserConversationOraclePhase = browserconversation.BrowserConversationOraclePhase
type BrowserConversationBrokerOperation = browserconversation.BrowserConversationBrokerOperation
type BrowserConversationTurnDirection = browserconversation.BrowserConversationTurnDirection
type BrowserConversationLifecycleOutcome = browserconversation.BrowserConversationLifecycleOutcome
type BrowserConversationValidatorStatus = browserconversation.BrowserConversationValidatorStatus
type BrowserConversationReportMetadata = browserconversation.BrowserConversationReportMetadata
type BrowserConversationReport = browserconversation.BrowserConversationReport
type BrowserConversationValidatorInput = browserconversation.BrowserConversationValidatorInput

const (
	BrowserConversationScenarioVersion         = browserconversation.BrowserConversationScenarioVersion
	BrowserConversationReportVersion           = browserconversation.BrowserConversationReportVersion
	BrowserConversationValidatorInputVersion   = browserconversation.BrowserConversationValidatorInputVersion
	BrowserInterruptOnInFlightInvocation       = browserconversation.BrowserInterruptOnInFlightInvocation
	BrowserConversationCustomerTurn            = browserconversation.BrowserConversationCustomerTurn
	BrowserConversationAssistantTurn           = browserconversation.BrowserConversationAssistantTurn
	BrowserConversationListTools               = browserconversation.BrowserConversationListTools
	BrowserConversationInvoke                  = browserconversation.BrowserConversationInvoke
	BrowserConversationCancel                  = browserconversation.BrowserConversationCancel
	BrowserConversationSelectPage              = browserconversation.BrowserConversationSelectPage
	BrowserConversationWaitReady               = browserconversation.BrowserConversationWaitReady
	BrowserConversationCustomerNavigate        = browserconversation.BrowserConversationCustomerNavigate
	BrowserConversationOracleBefore            = browserconversation.BrowserConversationOracleBefore
	BrowserConversationOracleAfter             = browserconversation.BrowserConversationOracleAfter
	BrowserConversationOraclePostSession       = browserconversation.BrowserConversationOraclePostSession
	BrowserConversationLifecycleCanceled       = browserconversation.BrowserConversationLifecycleCanceled
	BrowserConversationLifecycleCompleted      = browserconversation.BrowserConversationLifecycleCompleted
	BrowserConversationLifecycleNotStarted     = browserconversation.BrowserConversationLifecycleNotStarted
	BrowserConversationValidatorVersion        = browserconversation.BrowserConversationValidatorVersion
	BrowserConversationValidatorPass           = browserconversation.BrowserConversationValidatorPass
	BrowserConversationValidatorFail           = browserconversation.BrowserConversationValidatorFail
	BrowserConversationValidatorNotRun         = browserconversation.BrowserConversationValidatorNotRun
	ErrBrowserConversationSession              = browserconversation.ErrBrowserConversationSession
	ErrBrowserConversationValidatorStart       = browserconversation.ErrBrowserConversationValidatorStart
	ErrBrowserConversationValidatorFailed      = browserconversation.ErrBrowserConversationValidatorFailed
	ErrBrowserConversationValidatorTimeout     = browserconversation.ErrBrowserConversationValidatorTimeout
	ErrInvalidBrowserConversationScenario      = browserconversation.ErrInvalidBrowserConversationScenario
	ErrInvalidBrowserConversationResult        = browserconversation.ErrInvalidBrowserConversationResult
	ErrBrowserConversationRunFinalized         = browserconversation.ErrBrowserConversationRunFinalized
	ErrBrowserConversationDuplicateObservation = browserconversation.ErrBrowserConversationDuplicateObservation
	ErrBrowserConversationValidatorCommand     = browserconversation.ErrBrowserConversationValidatorCommand
	ErrBrowserConversationValidatorOutput      = browserconversation.ErrBrowserConversationValidatorOutput
	ErrBrowserConversationValidatorVerdict     = browserconversation.ErrBrowserConversationValidatorVerdict
)
