// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/roomreplaybundle"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/roomreplaybundle/internal/service"
)

// NewService assembles one stateless room-replay-bundle admission service.
func NewService() roomreplaybundle.Service {
	serviceService := service.New()
	return serviceService
}
