// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/selfplay"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/selfplay/internal"
)

// Injectors from service.go:

// NewService assembles self-play from explicit provider, catalog, and clock
// roles and returns only the public contract.
func NewService(deps Dependencies) selfplay.Service {
	sessionService := deps.SessionService
	modelCatalog := deps.ModelCatalog
	source := deps.Clock
	service := internal.NewService(sessionService, modelCatalog, source)
	return service
}
