// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/providers"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/selfplay"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/selfplay/internal/runtime"
	"github.com/portpowered/go-agent-harness/go-audio/pkg/clock"
)

// Injectors from providers.go:

func NewService(deps Dependencies) selfplay.Service {
	source := deps.Clock
	modelAdmission := deps.ModelAdmission
	sessionFactory := deps.Sessions
	sessionRunner := deps.Runner
	dependencies := newRuntimeDependencies(source, modelAdmission, sessionFactory, sessionRunner)
	service := runtime.New(dependencies)
	return service
}

// providers.go:

// Dependencies are the host ports required by one self-play runtime.
type Dependencies struct {
	Clock          clock.Source
	ModelAdmission providers.ModelAdmission
	Sessions       selfplay.SessionFactory
	Runner         selfplay.SessionRunner
}

func newRuntimeDependencies(source clock.Source, admission providers.ModelAdmission, sessions selfplay.SessionFactory, runner selfplay.SessionRunner) selfplay.Dependencies {
	return selfplay.Dependencies{Clock: source, ModelAdmission: admission, Sessions: sessions, Runner: runner}
}
