// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/conversationlog"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/conversationlog/internal/service"
	"github.com/portpowered/go-agent-harness/go-audio/pkg/clock"
)

// Injectors from providers.go:

// NewService constructs a reducer with the supplied wall-clock source. A nil
// source is valid and keeps timing out of deterministic snapshots.
func NewService(source clock.Source) conversationlog.Service {
	serviceService := service.New(source)
	return serviceService
}
