// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/roomplanning"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/roomplanning/internal/service"
)

// Injectors from wire.go:

func NewService(dependencies Dependencies) roomplanning.Service {
	roomplanningService := service.New()
	return roomplanningService
}

// wire.go:

type Dependencies struct{}
