// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/roomcapabilities"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/roomcapabilities/internal/service"
)

// Injectors from wire.go:

// NewService constructs an inert participant capability service. Every call to
// Compose receives explicit participant-local surfaces and returns independent
// snapshots and lifecycle callbacks.
func NewService() roomcapabilities.Service {
	serviceService := service.New()
	return serviceService
}
