// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/replay/wire"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/roomreplay"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/roomreplay/internal/service"
)

// Injectors from providers.go:

func NewService() roomreplay.Service {
	replayService := wire.NewService()
	serviceService := service.New(replayService)
	return serviceService
}
