// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/providerliveness"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/providerliveness/internal/service"
)

// Injectors from wire.go:

// NewService assembles one isolated provider-progress service.
func NewService(deps providerliveness.Dependencies) providerliveness.Service {
	serviceService := service.New(deps)
	return serviceService
}
