// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/session"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessiondiagnostics"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionturn"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionturn/internal/service"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/tools"
)

// Injectors from providers.go:

func NewService(deps Dependencies) sessionturn.Service {
	dependencies := newServiceDependencies(deps)
	serviceService := service.New(dependencies)
	return serviceService
}

// providers.go:

type Dependencies struct {
	Allocator          sessionturn.Allocator
	PolicyFactory      tools.InteractiveToolPolicyFactory
	ImageStaging       tools.ImageStaging
	ToolService        tools.Service
	InstructionService session.InstructionService
	LifecycleFactory   func() sessiondiagnostics.Service
}

func newServiceDependencies(deps Dependencies) service.Dependencies {
	return service.Dependencies{Allocator: deps.Allocator, PolicyFactory: deps.PolicyFactory, ImageStaging: deps.ImageStaging, ToolService: deps.ToolService, InstructionService: deps.InstructionService, LifecycleFactory: deps.LifecycleFactory}
}
