// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionturn"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionturn/internal/service"
)

// Injectors from providers.go:

func NewService(deps Dependencies) sessionturn.Service {
	dependencies := newServiceDependencies(deps)
	serviceService := service.New(dependencies)
	return serviceService
}

// providers.go:

type Dependencies struct {
	Allocator sessionturn.Allocator
}

func newServiceDependencies(deps Dependencies) service.Dependencies {
	return service.Dependencies{Allocator: deps.Allocator}
}
