// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/session"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionturn"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionturn/internal/service"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/tools"
)

// Injectors from wire.go:

// NewService assembles the session-turn implementation behind its public
// contract. Each service allocates its own text-seed sentinels.
func NewService(instructions session.InstructionService, policies tools.InteractiveToolPolicyFactory, staging tools.ImageStaging) sessionturn.Service {
	serviceService := service.New(instructions, policies, staging)
	return serviceService
}
