// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/browserrunner"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/browserrunner/internal/service"
)

// Injectors from providers.go:

// NewService assembles the browserrunner contracts and keeps the concrete
// tracker, interruption, and partition implementations private.
func NewService() browserrunner.Service {
	browserrunnerService := service.NewService()
	return browserrunnerService
}

// NewEvidenceTracker constructs the provider-neutral evidence tracker.
func NewEvidenceTracker(config browserrunner.EvidenceTrackerConfig) browserrunner.EvidenceTracker {
	evidenceTracker := service.NewEvidenceTracker(config)
	return evidenceTracker
}

// NewInterruptionController constructs the bounded event-driven audio
// interruption controller.
func NewInterruptionController(config browserrunner.InterruptionControllerConfig) browserrunner.InterruptionController {
	interruptionController := service.NewInterruptionController(config)
	return interruptionController
}
