// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/portpowered/go-agent-harness/agent-cli/internal/agent"
	"github.com/portpowered/go-agent-harness/agent-cli/internal/audio"
	"github.com/portpowered/go-agent-harness/agent-cli/internal/cli"
	"github.com/portpowered/go-agent-harness/agent-cli/internal/flags"
	"github.com/portpowered/go-agent-harness/agent-cli/internal/probe/fleet"
	"github.com/portpowered/go-agent-harness/agent-cli/internal/services"
	"github.com/portpowered/go-agent-harness/go-agent-loop/pkg/messages"
	"github.com/portpowered/go-agent-harness/go-llm-gateway/pkg/transport"
)

// Injectors from wire.go:

// assembleAgentCLI is the generated implementation shared by production and
// mock composition. Its parameters are explicit so the generated graph cannot
// hide a dependency behind a bag or locator.
func assembleAgentCLI(toolExecutor messages.ToolExecutor, transportDialer transport.Dialer, deviceRegistry DeviceRegistry, audioSource AudioSource, audioSink AudioSink, clockSource Clock, runtimeObserver SessionRuntimeObserver, toolDefs []messages.ToolDefinition, inferencer messages.Inferencer, sessionInferencer messages.SessionInferencer, rtcComponents services.SessionRTCComponents, relaxModelValidation bool, observer assemblyObserver) (*cli.AgentCLI, error) {
	globalFlags := flags.NewGlobalFlags()
	rootCommand := cli.NewRootCommand(globalFlags)
	v := provideModelValidation(relaxModelValidation, observer, toolExecutor, transportDialer, deviceRegistry, audioSource, audioSink, clockSource, runtimeObserver, inferencer, sessionInferencer)
	executor := agent.NewExecutor(toolExecutor, toolDefs, inferencer, v...)
	askFlags := flags.NewAskFlags()
	loopFlags := flags.NewLoopFlags()
	askCommand := cli.NewAskCommand(executor, askFlags, loopFlags, globalFlags)
	chatFlags := flags.NewChatFlags()
	chatCommand := cli.NewChatCommand(executor, askFlags, loopFlags, chatFlags, globalFlags)
	toolCommand := cli.NewToolCommand(globalFlags)
	interactionCommand := cli.NewInteractionCommand()
	interactionReplayCommand := cli.NewInteractionReplayCommand()
	probeCommand := cli.NewProbeCommand()
	v2 := provideProbeDeviceRegistries(deviceRegistry)
	probeRunCommand := cli.NewProbeRunCommand(v2...)
	probeGateCommand := cli.NewProbeGateCommand()
	probeReportCommand := cli.NewProbeReportCommand()
	v3 := provideFleetEntryExecutors()
	probeFleetCommand := cli.NewProbeFleetCommand(v3...)
	sessionToolCapabilitiesFactory := provideSessionToolCapabilitiesFactory(toolExecutor)
	sessionRTCRuntimeFactory := provideSessionRTCRuntimeFactory(rtcComponents)
	sessionCommand := cli.NewSessionCommandWithRuntimeAndDeviceRegistryAndToolCapabilitiesAndRTCRuntime(askFlags, globalFlags, toolExecutor, sessionInferencer, clockSource, runtimeObserver, sessionToolCapabilitiesFactory, deviceRegistry, sessionRTCRuntimeFactory)
	sessionShowCommand := cli.NewSessionShowCommand(globalFlags)
	sessionListCommand := cli.NewSessionListCommand(globalFlags)
	sessionDeleteCommand := cli.NewSessionDeleteCommand(globalFlags)
	configCommand := cli.NewConfigCommand()
	configAddLocalCommand := cli.NewConfigAddLocalCommand(globalFlags)
	v4 := provideAcceptanceCommands()
	router := cli.NewRouter(globalFlags, rootCommand, askCommand, chatCommand, toolCommand, interactionCommand, interactionReplayCommand, probeCommand, probeRunCommand, probeGateCommand, probeReportCommand, probeFleetCommand, sessionCommand, sessionShowCommand, sessionListCommand, sessionDeleteCommand, configCommand, configAddLocalCommand, v4...)
	agentCLI := cli.NewAgentCLI(router)
	return agentCLI, nil
}

// wire.go:

// provideSessionRTCRuntimeFactory installs the service-owned WebRTC runtime
// composition in the generated CLI graph. The component functions keep
// signaling, peer/data, and media implementations behind the service's
// provider-neutral contracts while leaving runtime side effects lazy until a
// session actually starts.
func provideSessionRTCRuntimeFactory(components services.SessionRTCComponents) services.SessionRTCRuntimeFactory {
	return services.NewSessionRTCRuntimeFactory(components)
}

func provideModelValidation(
	relaxModelValidation bool,
	observer assemblyObserver,
	toolExecutor messages.ToolExecutor,
	transportDialer transport.Dialer,
	deviceRegistry DeviceRegistry,
	audioSource AudioSource,
	audioSink AudioSink,
	clockSource Clock,
	runtimeObserver SessionRuntimeObserver,
	inferencer messages.Inferencer,
	sessionInferencer messages.SessionInferencer,
) []bool {
	if observer != nil {
		observer(compositionValues{
			toolExecutor:      toolExecutor,
			transportDialer:   transportDialer,
			deviceRegistry:    deviceRegistry,
			audioSource:       audioSource,
			audioSink:         audioSink,
			clockSource:       clockSource,
			runtimeObserver:   runtimeObserver,
			inferencer:        inferencer,
			sessionInferencer: sessionInferencer,
		})
	}
	return []bool{relaxModelValidation}
}

// FlagsSet provides global and command-specific CLI flags.
var FlagsSet = wire.NewSet(flags.NewGlobalFlags, flags.NewAskFlags, flags.NewChatFlags, flags.NewLoopFlags)

// provideFleetEntryExecutors keeps the production fleet command on its
// default transport dispatcher while leaving the executor injectable for
// hermetic command tests.
func provideFleetEntryExecutors() []fleet.EntryExecutor { return nil }

// provideAcceptanceCommands keeps the production router on its default
// acceptance runner while leaving the command injectable for route tests.
func provideAcceptanceCommands() []*cli.ProbeAcceptanceCommand { return nil }

// provideProbeDeviceRegistries adapts the shared application registry to the
// variadic probe constructor. Keeping the adapter in the source graph makes
// the generated call retain the same device implementation as the session
// command and device routes.
func provideProbeDeviceRegistries(registry DeviceRegistry) []audio.DeviceRegistry {
	return []audio.DeviceRegistry{registry}
}

// CliSet provides CLI commands, router, and root.
var CliSet = wire.NewSet(
	FlagsSet, cli.NewRootCommand, cli.NewAskCommand, cli.NewChatCommand, cli.NewToolCommand, cli.NewInteractionCommand, cli.NewInteractionReplayCommand, cli.NewProbeCommand, cli.NewProbeRunCommand, cli.NewProbeGateCommand, cli.NewProbeReportCommand, cli.NewProbeFleetCommand, provideFleetEntryExecutors,
	provideAcceptanceCommands,
	provideProbeDeviceRegistries,
	provideSessionToolCapabilitiesFactory,
	provideSessionRTCRuntimeFactory, cli.NewSessionCommandWithRuntimeAndDeviceRegistryAndToolCapabilitiesAndRTCRuntime, cli.NewSessionShowCommand, cli.NewSessionListCommand, cli.NewSessionDeleteCommand, cli.NewConfigCommand, cli.NewConfigAddLocalCommand, cli.NewRouter, cli.NewAgentCLI,
)
