// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/portpowered/go-agent-harness/agent-cli/internal/agent"
	"github.com/portpowered/go-agent-harness/agent-cli/internal/audio"
	"github.com/portpowered/go-agent-harness/agent-cli/internal/cli"
	"github.com/portpowered/go-agent-harness/agent-cli/internal/flags"
	"github.com/portpowered/go-agent-harness/go-agent-loop/pkg/messages"
	"github.com/portpowered/go-agent-harness/go-agent-loop/pkg/platform/clock"
)

// Injectors from wire.go:

// assembleAgentCLI is the generated implementation shared by production and
// mock composition. Its parameters are explicit so the generated graph cannot
// hide a dependency behind a bag or locator.
func assembleAgentCLI(toolExecutor messages.ToolExecutor, deviceRegistry DeviceRegistry, audioSource audio.AudioSource, audioSink AudioSink, clockSource clock.Source, toolDefs []messages.ToolDefinition, inferencer messages.Inferencer, sessionInferencer messages.SessionInferencer, relaxModelValidation bool) (*cli.AgentCLI, error) {
	globalFlags := flags.NewGlobalFlags()
	rootCommand := cli.NewRootCommand(globalFlags)
	v := provideModelValidation(relaxModelValidation)
	executor := agent.NewExecutor(toolExecutor, toolDefs, inferencer, v...)
	askFlags := flags.NewAskFlags()
	loopFlags := flags.NewLoopFlags()
	askCommand := cli.NewAskCommand(executor, askFlags, loopFlags, globalFlags)
	chatFlags := flags.NewChatFlags()
	chatCommand := cli.NewChatCommand(executor, askFlags, loopFlags, chatFlags, globalFlags)
	toolCommand := cli.NewToolCommand(globalFlags)
	interactionCommand := cli.NewInteractionCommand()
	interactionReplayCommand := cli.NewInteractionReplayCommand()
	sessionCommand := cli.NewSessionCommand(askFlags, globalFlags, sessionInferencer)
	sessionShowCommand := cli.NewSessionShowCommand(globalFlags)
	sessionListCommand := cli.NewSessionListCommand(globalFlags)
	sessionDeleteCommand := cli.NewSessionDeleteCommand(globalFlags)
	configCommand := cli.NewConfigCommand()
	configAddLocalCommand := cli.NewConfigAddLocalCommand(globalFlags)
	router := cli.NewRouter(globalFlags, rootCommand, askCommand, chatCommand, toolCommand, interactionCommand, interactionReplayCommand, sessionCommand, sessionShowCommand, sessionListCommand, sessionDeleteCommand, configCommand, configAddLocalCommand)
	agentCLI := cli.NewAgentCLI(router)
	return agentCLI, nil
}

// wire.go:

func provideModelValidation(relaxModelValidation bool) []bool {
	return []bool{relaxModelValidation}
}

// FlagsSet provides global and command-specific CLI flags.
var FlagsSet = wire.NewSet(flags.NewGlobalFlags, flags.NewAskFlags, flags.NewChatFlags, flags.NewLoopFlags)

// CliSet provides CLI commands, router, and root.
var CliSet = wire.NewSet(
	FlagsSet, cli.NewRootCommand, cli.NewAskCommand, cli.NewChatCommand, cli.NewToolCommand, cli.NewInteractionCommand, cli.NewInteractionReplayCommand, cli.NewSessionCommand, cli.NewSessionShowCommand, cli.NewSessionListCommand, cli.NewSessionDeleteCommand, cli.NewConfigCommand, cli.NewConfigAddLocalCommand, cli.NewRouter, cli.NewAgentCLI,
)
