// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/metricsreplay"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/metricsreplay/internal/service"
)

// Injectors from providers.go:

// NewService assembles one invocation-neutral metrics replay service from
// explicit host dependencies.
func NewService(deps metricsreplay.Dependencies) metricsreplay.Service {
	service := newService(deps)
	return service
}

// providers.go:

func newService(deps metricsreplay.Dependencies) *service.Service {
	return service.New(service.Dependencies{
		Clock:   deps.Clock,
		Runner:  deps.Runner,
		Loader:  deps.Loader,
		NewSink: deps.NewSink,
	})
}
