// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionfinalization"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionfinalization/internal/service"
)

// NewService returns the reusable finalization contract.
func NewService() sessionfinalization.Service {
	return service.New()
}
