// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionfinalization"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionfinalization/internal/service"
)

func NewService() sessionfinalization.Service {
	return service.New()
}
