// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessioncontinuation"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessioncontinuation/internal/service"
)

// Injectors from wire.go:

// NewService constructs the inert continuation policy service.
func NewService() sessioncontinuation.Service {
	serviceService := service.New()
	return serviceService
}
