// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/devicebinding"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/devicebinding/internal/service"
)

// Injectors from providers.go:

// NewService returns a stateless service whose Open method performs admission.
func NewService() devicebinding.Service {
	serviceService := service.New()
	return serviceService
}
