// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/session/wire"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionduration"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionduration/internal/service"
)

// Injectors from wire.go:

// NewService assembles the terminal-boundary implementation behind its public
// host-neutral contract.
func NewService() sessionduration.Service {
	serviceService := service.New()
	return serviceService
}

// wire.go:

// NewDuplexLoopFactory constructs the session-owned loop factory from the
// session service's local Wire graph.
func NewDuplexLoopFactory() sessionduration.DuplexLoopFactory {
	return wire.NewDuplexLoopFactory()
}
