// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/roomreplayschedule"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/roomreplayschedule/internal/service"
)

// Injectors from wire.go:

// NewService assembles the credential-free room replay scheduling service.
func NewService() roomreplayschedule.Service {
	serviceService := service.New()
	return serviceService
}
