#!/usr/bin/env python3
"""Verify the C119 service extraction, ownership, and causal controls."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
from typing import Any


EVIDENCE_DIR = Path(__file__).resolve().parent
ROOT = EVIDENCE_DIR.parents[4]
RUNTIME = ROOT / "go-agent-runtime"
ADMISSION = EVIDENCE_DIR / "admission.json"
LEGACY = ROOT / "agent-cli/internal/services/internal/agentruntime/session_diagnostics_failure.go"
ADAPTER = ROOT / "agent-cli/internal/services/internal/agentruntime/session_failure_projection_adapter.go"
BASELINE = "3963bc3566da24f8214634c17a9d0f79a6724171"
STARTUP = "8bdafc7f947a3a2c9856220abdc539437035bd21"
BASELINE_LINES = 246
BASELINE_SHA256 = "c6531d0c2a0f3556c2bc478f911a1687242456fd6ba920f370aa51eb0e7ecfd6"
CURRENT_MAIN = "origin/main"
WIRE_REGISTRY = "scripts/wire-packages.txt"
ARCHITECTURE_POLICY = "docs/architecture/architecture-policy.json"
ARCHITECTURE_BASELINE = "docs/architecture/baselines/github.com/portpowered/go-agent-harness/agent-cli/internal/services/internal/agentruntime/_package.json"
SESSIONFAILURE_WIRE = "go-agent-runtime/services/sessionfailure/wire"
SESSIONFAILURE_WIRE_RULE = {
    "module": "go-agent-runtime",
    "pattern": "services/sessionfailure/wire/wire_gen.go",
    "generator": "wire",
    "header": "// Code generated by Wire. DO NOT EDIT.",
}
OWNED = (
    "agent-cli/internal/services/internal/agentruntime/session_diagnostics_failure.go",
    "agent-cli/internal/services/internal/agentruntime/session_failure_projection_adapter.go",
    "agent-cli/internal/services/internal/agentruntime/session_failure_projection_test.go",
    "go-agent-runtime/services/sessionfailure/",
    "coverage-manifest/go-agent-runtime/services/sessionfailure/",
    "docs/temp/projects/audio-runtime/audio-runtime-c119-retire-cli-session-failure-projection/",
)
FORBIDDEN = {
    "agent-cli/internal/services/internal/agentruntime/session_diagnostics.go": "0584e3acc16e29b8fb79ece8a19199f0f8690de39099af922f08781edd957eb8",
    "agent-cli/internal/services/internal/agentruntime/session_diagnostics_observation.go": "400eba47b433673f95929d56d68f2d610cd145eab99d0712f571f1125a6c0281",
    "agent-cli/internal/services/internal/agentruntime/session_diagnostics_terminal.go": "4608c5c35277c97375c89e989e8a9c88dc6376968239ee66d713a0ee3f65b369",
    "agent-cli/internal/services/internal/agentruntime/session_room_terminal.go": "50c9c02f61a822c5e20c97dad59b8627c171f9ba85a85d2bb3d496fb2b760b57",
    "agent-cli/internal/services/internal/agentruntime/session_liveness.go": "d9de111ed44d79045cdc492a7309314cad81c7e478ee8a2fea7a1c9755d2eb17",
    "agent-cli/internal/services/internal/agentruntime/session_cancellation.go": "bdb7e50876bd8d9b67fe04a736da9a91ce3ea2bbd10024ebf27d0f6bbbcd9edd",
    "agent-cli/internal/services/internal/agentruntime/session_room_coordinator.go": "11fae882fa7232b6c6b797d4bdbf45428e4e49efba7d74dd4e43609dcc59fa92",
    "agent-cli/internal/services/internal/agentruntime/session_room_lifecycle.go": "33acf07ea4f4a71fcf332674efbcecf70a0a01c067c626c5b85fae625e8903ec",
    "agent-cli/internal/services/internal/agentruntime/session_room_run.go": "2ac0ff50ee59a1ec8f04682e04d876d270146ecda8245c5d14d28a5f7120e8d6",
    "agent-cli/internal/services/internal/agentruntime/session_tool_lifecycle.go": "48000dcd73b85ebbe93fd40a3996529878a99c799b67b0779d60f55dbb43fc1e",
}

SHARED_RECONCILIATION = (WIRE_REGISTRY, ARCHITECTURE_POLICY, ARCHITECTURE_BASELINE)


class VerificationFailure(RuntimeError):
    pass


def require(condition: bool, message: str) -> None:
    if not condition:
        raise VerificationFailure(message)


def digest(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def git(*args: str) -> str:
    result = subprocess.run(["rtk", "proxy", "git", *args], cwd=ROOT, capture_output=True, text=True, check=False, timeout=30)
    require(result.returncode == 0, result.stderr.strip() or f"git {' '.join(args)} failed")
    return result.stdout.strip()


def git_bytes(*args: str) -> bytes:
    result = subprocess.run(["rtk", "proxy", "git", *args], cwd=ROOT, capture_output=True, check=False, timeout=30)
    require(result.returncode == 0, result.stderr.decode(errors="replace").strip() or f"git {' '.join(args)} failed")
    return result.stdout


def scrubbed_environment() -> dict[str, str]:
    environment = os.environ.copy()
    for name in list(environment):
        if name.endswith("_API_KEY") or name in {"OPENAI_API_KEY", "REALTIME_API_KEY", "YUI_API_KEY"}:
            del environment[name]
    environment["GOWORK"] = "off"
    return environment


def command(argv: list[str], cwd: Path, timeout: float = 180.0, gowork: str = "off") -> dict[str, Any]:
    environment = scrubbed_environment()
    environment["GOWORK"] = gowork
    result = subprocess.run(argv, cwd=cwd, env=environment, stdin=subprocess.DEVNULL, capture_output=True, text=True, check=False, timeout=timeout)
    return {"argv": argv, "cwd": str(cwd), "exit_code": result.returncode, "stdout": result.stdout[-65536:], "stderr": result.stderr[-65536:]}


def baseline_source() -> bytes:
    result = subprocess.run(["rtk", "proxy", "git", "show", f"{BASELINE}:agent-cli/internal/services/internal/agentruntime/session_diagnostics_failure.go"], cwd=ROOT, capture_output=True, check=False, timeout=30)
    require(result.returncode == 0, result.stderr.decode(errors="replace"))
    return result.stdout


def changed_paths() -> list[str]:
    # After C79 release, origin/main is the predecessor checkpoint. The old
    # accepted-main diff also contains C79's released files, so it cannot be
    # used as the candidate scope boundary after that required merge.
    paths = set(filter(None, git("diff", "--name-only", f"{CURRENT_MAIN}...HEAD").splitlines()))
    paths.update(filter(None, git("diff", "--name-only").splitlines()))
    paths.update(filter(None, git("diff", "--cached", "--name-only").splitlines()))
    paths.update(filter(None, git("ls-files", "--others", "--exclude-standard").splitlines()))
    return sorted(paths)


def verify_shared_reconciliation() -> dict[str, Any]:
    """Allow only the released C119 Wire registration on shared policy files."""
    registry = (ROOT / WIRE_REGISTRY).read_text(encoding="utf-8").splitlines()
    main_registry = git("show", f"{CURRENT_MAIN}:{WIRE_REGISTRY}").splitlines()
    require(registry.count(SESSIONFAILURE_WIRE) == 1, "sessionfailure Wire registry entry is missing or duplicated")
    require(main_registry.count(SESSIONFAILURE_WIRE) == 0, "origin/main already contains an unexpected sessionfailure Wire registry entry")
    try:
        insert_at = main_registry.index("go-agent-runtime/services/sessiondiagnostics/wire") + 1
    except ValueError as exc:
        raise VerificationFailure("origin/main Wire registry lacks the sessiondiagnostics anchor") from exc
    expected_registry = main_registry[:insert_at] + [SESSIONFAILURE_WIRE] + main_registry[insert_at:]
    require(registry == expected_registry, "shared Wire registry contains changes beyond sessionfailure registration")

    policy = json.loads((ROOT / ARCHITECTURE_POLICY).read_text(encoding="utf-8"))
    main_policy = json.loads(git("show", f"{CURRENT_MAIN}:{ARCHITECTURE_POLICY}"))
    main_rules = list(main_policy.get("generated_files", []))
    expected_rules = main_rules if SESSIONFAILURE_WIRE_RULE in main_rules else main_rules + [SESSIONFAILURE_WIRE_RULE]
    require(policy.get("generated_files") == expected_rules, "architecture policy contains changes beyond sessionfailure Wire registration")
    policy_without_rules = dict(policy)
    main_policy_without_rules = dict(main_policy)
    policy_without_rules.pop("generated_files", None)
    main_policy_without_rules.pop("generated_files", None)
    require(policy_without_rules == main_policy_without_rules, "architecture policy contains unrelated changes")

    baseline = (ROOT / ARCHITECTURE_BASELINE).read_bytes()
    main_baseline = git_bytes("show", f"{CURRENT_MAIN}:{ARCHITECTURE_BASELINE}")
    require(baseline == main_baseline, "architecture baseline changed without a demonstrated C119 downward entry")
    return {"wire_registry": WIRE_REGISTRY, "architecture_policy": ARCHITECTURE_POLICY, "architecture_baseline_unchanged": True}


def verify_admission() -> dict[str, Any]:
    data = json.loads(ADMISSION.read_text(encoding="utf-8"))
    require(data["project"] == "audio-runtime" and data["contractRevision"] == "audio-runtime-v1", "admitted project or contract changed")
    require(data["verifyWork"]["status"] == "admitted" and data["secondProject"] is False and data["acceptanceWaiver"] is False, "admission is not sole-project and waiver-free")
    require(data["branch"] == git("branch", "--show-current"), "current branch differs from admitted branch")
    prd = json.loads((ROOT / "prd.json").read_text(encoding="utf-8"))
    require(prd["branchName"] == data["branch"], "prd.branchName differs from current branch")
    source = baseline_source()
    require(len(source.splitlines()) == BASELINE_LINES and digest(source) == BASELINE_SHA256, "immutable source baseline changed")
    for revision, label in ((STARTUP, "startup"), (BASELINE, "accepted main")):
        result = subprocess.run(["rtk", "proxy", "git", "merge-base", "--is-ancestor", revision, "HEAD"], cwd=ROOT, capture_output=True, check=False, timeout=30)
        require(result.returncode == 0, f"{label} is not an ancestor")
    return {"project": data["project"], "contract_revision": data["contractRevision"], "branch": data["branch"], "baseline": BASELINE}


def verify_scope() -> dict[str, Any]:
    paths = changed_paths()
    outside = [path for path in paths if path not in SHARED_RECONCILIATION and not any(path == prefix or path.startswith(prefix) for prefix in OWNED)]
    require(not outside, f"changed path outside C119 ownership: {outside}")
    forbidden_changed = sorted(path for path in paths if path in FORBIDDEN)
    require(not forbidden_changed, f"excluded caller/shared path changed: {forbidden_changed}")
    for path in FORBIDDEN:
        current = ROOT / path
        accepted_main = git_bytes("show", f"{CURRENT_MAIN}:{path}")
        require(current.is_file() and current.read_bytes() == accepted_main, f"excluded fingerprint changed from current origin/main: {path}")
    require(not LEGACY.exists(), "legacy session failure source remains")
    require(ADAPTER.is_file() and len(ADAPTER.read_text(encoding="utf-8").splitlines()) <= 86, "compatibility adapter exceeds 86 physical lines")
    required = (
        RUNTIME / "services/sessionfailure/contract.go",
        RUNTIME / "services/sessionfailure/internal/service/service.go",
        RUNTIME / "services/sessionfailure/wire/providers.go",
        RUNTIME / "services/sessionfailure/wire/wire_gen.go",
    )
    for path in required:
        require(path.is_file(), f"required service file missing: {path}")
    source = "\n".join(path.read_text(encoding="utf-8") for path in (RUNTIME / "services/sessionfailure").rglob("*.go"))
    for forbidden in ("agent-cli", "os.Getenv", "os.LookupEnv", "func init(", "time.Sleep", "flag."):
        require(forbidden not in source, f"runtime service contains forbidden host policy: {forbidden}")
    return {"changed_paths": paths, "shared_reconciliation": verify_shared_reconciliation(), "adapter_lines": len(ADAPTER.read_text(encoding="utf-8").splitlines()), "retired_cli_lines": BASELINE_LINES}


def focused_checks() -> list[dict[str, Any]]:
    checks = [
        (["rtk", "proxy", "env", "GOWORK=off", "go", "test", "./services/sessionfailure/...", "-run", "Normalize|Facts|Accept|Projection|Wire|Nil|Contract", "-count=3", "-timeout=180s"], RUNTIME, 180.0),
        (["rtk", "proxy", "env", "GOWORK=off", "go", "test", "-race", "./services/sessionfailure/...", "-run", "Accept|Projection|Wire|Contract", "-count=3", "-timeout=240s"], RUNTIME, 240.0),
        (["rtk", "proxy", "env", "GOWORK=off", "go", "test", "./...", "-count=1", "-timeout=120s"], EVIDENCE_DIR / "external-consumer", 120.0),
        (["rtk", "proxy", "go", "test", "./agent-cli/internal/services/internal/agentruntime", "-run", "TestSessionFailureProjection_Adapter|TestSessionProgressObserver_IgnoresNonTerminalProviderDiagnostic|TestSessionDiagnostics_ConnectPhaseFailureEmitsOneCanonicalRecord|TestSessionDiagnostics_MidStreamFailureEmitsOneCanonicalRecord|TestSessionDiagnostics_DrainPhaseFailureEmitsOneCanonicalRecord|TestSessionDiagnostics_CleanCloseProducesNoFailureRecord|TestSessionSIGINTCancellationDoesNotSuppressIndependentFailure", "-count=1", "-timeout=240s"], ROOT, 240.0),
    ]
    records = []
    for argv, cwd, timeout in checks:
        record = command(argv, cwd, timeout, str(ROOT / "go.work") if cwd == ROOT else "off")
        require(record["exit_code"] == 0, f"focused command failed: {record}")
        records.append(record)
    return records


def mutation_check(name: str, replacement: tuple[str, str], run_pattern: str) -> dict[str, Any]:
    with tempfile.TemporaryDirectory(prefix=f"c119-{name}-") as directory:
        root = Path(directory)
        package = root / "services/sessionfailure"
        internal = package / "internal/service"
        internal.mkdir(parents=True)
        shutil.copy2(RUNTIME / "services/sessionfailure/contract.go", package / "contract.go")
        service_source = (RUNTIME / "services/sessionfailure/internal/service/service.go").read_text(encoding="utf-8")
        before, after = replacement
        require(before in service_source, f"mutation anchor missing for {name}")
        mutated = service_source.replace(before, after, 1)
        (internal / "service.go").write_text(mutated, encoding="utf-8")
        shutil.copy2(RUNTIME / "services/sessionfailure/internal/service/service_test.go", internal / "service_test.go")
        (root / "go.mod").write_text("module github.com/portpowered/go-agent-harness/go-agent-runtime\n\ngo 1.26.7\n\nrequire (\n github.com/portpowered/go-agent-harness/go-agent-loop v0.0.3\n github.com/portpowered/go-agent-harness/go-audio v0.0.0\n)\n\nreplace github.com/portpowered/go-agent-harness/go-agent-loop => " + str(ROOT / "go-agent-loop") + "\nreplace github.com/portpowered/go-agent-harness/go-audio => " + str(ROOT / "go-audio") + "\n", encoding="utf-8")
        tidy = command(["rtk", "proxy", "env", "GOWORK=off", "go", "mod", "tidy"], root, 120.0)
        require(tidy["exit_code"] == 0, f"mutation module setup failed for {name}: {tidy}")
        record = command(["rtk", "proxy", "env", "GOWORK=off", "go", "test", "./services/sessionfailure/internal/service", "-run", run_pattern, "-count=1", "-timeout=120s"], root, 120.0)
        output = record["stdout"] + record["stderr"]
        require("--- FAIL:" in output, f"causal mutant {name} did not fail a targeted oracle: {record}")
        require(record["exit_code"] != 0, f"causal mutant {name} survived: {record}")
        return {"name": name, "survived": False, "exit_code": record["exit_code"], "failure_output": output[-8192:]}


def causal_mutations() -> list[dict[str, Any]]:
    return [
        mutation_check("drop-terminal-facts", ("return facts, err", "return sessionfailure.Facts{}, nil"), "TestNormalizeErrorValue|TestFactsFromSessionRunError"),
        mutation_check("convert-cancellation-to-failure", ("return v.TerminalReason == messages.TerminalReasonCancellation ||", "return false ||"), "TestNormalizeErrorValue|TestFactsFromSessionRunError"),
    ]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", choices=("excluded-paths-and-adapter", "positive-and-two-mutations", "retirement-and-owned-paths", "final"), default="excluded-paths-and-adapter")
    parser.add_argument("--base", default=BASELINE)
    args = parser.parse_args()
    try:
        require(args.base == BASELINE, f"verification base must remain accepted main {BASELINE}")
        report: dict[str, Any] = {"schema": "audio-runtime.c119.verification.v1", "mode": args.mode, "admission": verify_admission(), "scope": verify_scope()}
        if args.mode in {"positive-and-two-mutations", "final"}:
            report["checks"] = focused_checks()
            report["mutations"] = causal_mutations()
        report["status"] = "accepted"
        ARTIFACTS = EVIDENCE_DIR / "artifacts"
        ARTIFACTS.mkdir(parents=True, exist_ok=True)
        artifact = ARTIFACTS / f"verify-{os.getpid()}.json"
        artifact.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        report["artifact"] = str(artifact)
        print(json.dumps(report, sort_keys=True))
        return 0
    except (OSError, json.JSONDecodeError, subprocess.SubprocessError, VerificationFailure) as exc:
        print(json.dumps({"schema": "audio-runtime.c119.verification.v1", "mode": args.mode, "status": "failed", "error": str(exc)}, sort_keys=True))
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
