// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessioninstructions"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessioninstructions/internal/service"
)

// Injectors from wire.go:

// NewInstructionService assembles the stateless instruction policy service.
func NewInstructionService() sessioninstructions.InstructionService {
	v := service.New()
	return v
}
