#!/usr/bin/env python3
"""Discover, regenerate, and verify every Wire injector in workspace modules."""

import argparse
import difflib
import os
from pathlib import Path
import subprocess
import sys


GENERATED_HEADER = "Code generated by Wire. DO NOT EDIT."
WIRE_DIRECTIVE = "github.com/google/wire/cmd/wire"


def _module_directories(root, modules):
    directories = []
    for module in modules:
        directory = (root / module).resolve()
        if not directory.is_relative_to(root) or not (directory / "go.mod").is_file():
            raise ValueError(f"missing or invalid module: {module}")
        directories.append(directory)
    return directories


def _wire_injector(source):
    contents = source.read_text()
    return "//go:build wireinject" in contents or "// +build wireinject" in contents


def discovered_packages(root, modules):
    """Return sorted Wire package paths and fail closed on malformed pairs."""
    root = root.resolve()
    generated_by_directory = {}
    injectors_by_directory = {}
    for module in _module_directories(root, modules):
        for generated in module.rglob("wire_gen.go"):
            generated_by_directory[generated.parent] = generated
        for source in module.rglob("*.go"):
            if source.name != "wire_gen.go" and _wire_injector(source):
                injectors_by_directory.setdefault(source.parent, []).append(source)

    directories = set(generated_by_directory) | set(injectors_by_directory)
    if not directories:
        raise ValueError("no Wire packages discovered")
    entries = []
    for directory in sorted(directories, key=lambda item: item.relative_to(root).as_posix()):
        entry = directory.relative_to(root).as_posix()
        generated = generated_by_directory.get(directory)
        injectors = sorted(injectors_by_directory.get(directory, []))
        if generated is None:
            raise ValueError(f"orphan Wire injector without wire_gen.go: {entry}")
        if not injectors:
            raise ValueError(f"orphan wire_gen.go without a wireinject source: {entry}")
        if len(injectors) != 1:
            names = [source.name for source in injectors]
            raise ValueError(f"Wire package must have exactly one wireinject source: {entry}: {names}")
        injector_contents = injectors[0].read_text()
        directives = []
        for line in injector_contents.splitlines():
            if not line.startswith("//go:generate "):
                continue
            command = line.removeprefix("//go:generate ").strip().split()
            if WIRE_DIRECTIVE in line or (command and command[0] == "wire"):
                directives.append(line)
        if len(directives) != 1:
            raise ValueError(f"Wire injector requires exactly one reproducible generation directive: {entry}")
        if "wire.Build(" not in injector_contents:
            raise ValueError(f"Wire injector does not call wire.Build: {entry}")
        generated_contents = generated.read_text()
        if GENERATED_HEADER not in generated_contents:
            raise ValueError(f"missing Wire generated header: {entry}")
        if "//go:build !wireinject" not in generated_contents:
            raise ValueError(f"generated Wire graph lacks !wireinject build constraint: {entry}")
        entries.append(entry)
    return entries


def check(root, modules, go):
    root = root.resolve()
    entries = discovered_packages(root, modules)
    before = {entry: (root / entry / "wire_gen.go").read_bytes() for entry in entries}
    env = dict(os.environ, GOWORK="off")
    for entry in entries:
        print(f"==> Wire {entry}", flush=True)
        subprocess.run([go, "generate", "."], cwd=root / entry, env=env, check=True)
    if discovered_packages(root, modules) != entries:
        raise ValueError("Wire package inventory changed during regeneration")
    changed = False
    for entry, original in before.items():
        path = root / entry / "wire_gen.go"
        current = path.read_bytes()
        if current != original:
            changed = True
            sys.stderr.writelines(difflib.unified_diff(
                original.decode().splitlines(keepends=True),
                current.decode().splitlines(keepends=True),
                fromfile=f"before/{entry}/wire_gen.go",
                tofile=f"after/{entry}/wire_gen.go",
            ))
    if changed:
        raise ValueError("Wire generated code changed; review and commit regenerated graphs")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--go", default="go")
    parser.add_argument("modules", nargs="+")
    args = parser.parse_args()
    try:
        check(args.root, args.modules, args.go)
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        print(f"wire-check: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
