#!/usr/bin/env python3
"""Discover, regenerate, and verify every Wire injector in workspace modules."""

import argparse
import concurrent.futures
import difflib
import os
from pathlib import Path
import subprocess
import sys


GENERATED_HEADER = "Code generated by Wire. DO NOT EDIT."
WIRE_DIRECTIVE = "github.com/google/wire/cmd/wire"


def _module_directories(root, modules):
    directories = []
    for module in modules:
        directory = (root / module).resolve()
        if not directory.is_relative_to(root) or not (directory / "go.mod").is_file():
            raise ValueError(f"missing or invalid module: {module}")
        directories.append(directory)
    return directories


def _wire_injector(source):
    contents = source.read_text()
    return "//go:build wireinject" in contents or "// +build wireinject" in contents


# The only go:generate commands check() treats as Wire, split into words.
# check() runs the pinned form itself with `gen <packages>` appended, so any
# other command, including wire with flags or extra arguments, or a shell
# that also runs something else, is not reproduced and must be rejected.
WIRE_COMMANDS = (
    ("go", "run", "-mod=mod", WIRE_DIRECTIVE),
    ("wire",),
)


def _generate_command(line):
    """Return the command of a go:generate line, or None for other lines.

    Mirrors cmd/go's isGoGenerate: the directive is `//go:generate` followed
    by a space or a tab.
    """
    if line.startswith("//go:generate ") or line.startswith("//go:generate\t"):
        return line[len("//go:generate"):].strip()
    return None


def _wire_directive(command):
    return tuple(command.split()) in WIRE_COMMANDS


def _foreign_directives(directory):
    """Return go:generate lines in a Wire package that are not exact Wire runs.

    check() regenerates with one `wire gen` per module instead of
    `go generate` per package, so a package whose go:generate would run
    anything else (another generator, wire with other arguments, a compound
    shell command) must fail closed rather than silently skip it.
    """
    foreign = []
    for source in sorted(directory.glob("*.go")):
        for line in source.read_text().splitlines():
            command = _generate_command(line)
            if command is not None and not _wire_directive(command):
                foreign.append(f"{source.name}: {line}")
    return foreign


def discovered_packages(root, modules):
    """Return sorted Wire package paths and fail closed on malformed pairs."""
    root = root.resolve()
    generated_by_directory = {}
    injectors_by_directory = {}
    for module in _module_directories(root, modules):
        for generated in module.rglob("wire_gen.go"):
            generated_by_directory[generated.parent] = generated
        for source in module.rglob("*.go"):
            if source.name != "wire_gen.go" and _wire_injector(source):
                injectors_by_directory.setdefault(source.parent, []).append(source)

    directories = set(generated_by_directory) | set(injectors_by_directory)
    if not directories:
        raise ValueError("no Wire packages discovered")
    entries = []
    for directory in sorted(directories, key=lambda item: item.relative_to(root).as_posix()):
        entry = directory.relative_to(root).as_posix()
        generated = generated_by_directory.get(directory)
        injectors = sorted(injectors_by_directory.get(directory, []))
        if generated is None:
            raise ValueError(f"orphan Wire injector without wire_gen.go: {entry}")
        if not injectors:
            raise ValueError(f"orphan wire_gen.go without a wireinject source: {entry}")
        if len(injectors) != 1:
            names = [source.name for source in injectors]
            raise ValueError(f"Wire package must have exactly one wireinject source: {entry}: {names}")
        injector_contents = injectors[0].read_text()
        directives = []
        for line in injector_contents.splitlines():
            command = _generate_command(line)
            if command is not None and _wire_directive(command):
                directives.append(line)
        if len(directives) != 1:
            raise ValueError(f"Wire injector requires exactly one reproducible generation directive: {entry}")
        foreign = _foreign_directives(directory)
        if foreign:
            raise ValueError(f"Wire package has a non-Wire go:generate directive: {entry}: {foreign}")
        if "wire.Build(" not in injector_contents:
            raise ValueError(f"Wire injector does not call wire.Build: {entry}")
        generated_contents = generated.read_text()
        if GENERATED_HEADER not in generated_contents:
            raise ValueError(f"missing Wire generated header: {entry}")
        if "//go:build !wireinject" not in generated_contents:
            raise ValueError(f"generated Wire graph lacks !wireinject build constraint: {entry}")
        entries.append(entry)
    return entries


def check(root, modules, go):
    root = root.resolve()
    entries = discovered_packages(root, modules)
    before = {entry: (root / entry / "wire_gen.go").read_bytes() for entry in entries}
    env = dict(os.environ, GOWORK="off")

    # One `wire gen` per module regenerates every Wire package of that module
    # from a single package load, so dependencies shared by the graphs are
    # type-checked once instead of once per package. It is the command each
    # package's go:generate directive runs (`go run -mod=mod <wire>` from
    # inside the module, so the module's pinned Wire version), and
    # discovered_packages rejects any other go:generate directive in a Wire
    # package, so no generator that `go generate .` would have run is
    # skipped. Modules are independent and regenerate concurrently; the first
    # generator failure is re-raised.
    module_names = sorted((Path(module).as_posix() for module in modules), key=len, reverse=True)
    groups = {}
    for entry in entries:
        owner = next((name for name in module_names if entry.startswith(name + "/")), None)
        if owner is None:
            raise ValueError(f"Wire package is outside the checked modules: {entry}")
        groups.setdefault(owner, []).append(entry)

    def regenerate(owner, group):
        print(f"==> Wire {owner}: {' '.join(group)}", flush=True)
        packages = ["./" + Path(entry).relative_to(owner).as_posix() for entry in group]
        subprocess.run(
            [go, "run", "-mod=mod", WIRE_DIRECTIVE, "gen", *packages],
            cwd=root / owner, env=env, check=True,
        )

    with concurrent.futures.ThreadPoolExecutor(max_workers=len(groups)) as pool:
        futures = [pool.submit(regenerate, owner, group) for owner, group in groups.items()]
        for future in futures:
            future.result()
    if discovered_packages(root, modules) != entries:
        raise ValueError("Wire package inventory changed during regeneration")
    changed = False
    for entry, original in before.items():
        path = root / entry / "wire_gen.go"
        current = path.read_bytes()
        if current != original:
            changed = True
            sys.stderr.writelines(difflib.unified_diff(
                original.decode().splitlines(keepends=True),
                current.decode().splitlines(keepends=True),
                fromfile=f"before/{entry}/wire_gen.go",
                tofile=f"after/{entry}/wire_gen.go",
            ))
    if changed:
        raise ValueError("Wire generated code changed; review and commit regenerated graphs")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--go", default="go")
    parser.add_argument("modules", nargs="+")
    args = parser.parse_args()
    try:
        check(args.root, args.modules, args.go)
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        print(f"wire-check: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
