#!/usr/bin/env python3
"""Regenerate every registered Wire injector and reject generated-code drift."""

import argparse
import difflib
import os
from pathlib import Path
import subprocess
import sys


def registered_packages(root, manifest, modules):
    entries = [
        line.strip()
        for line in manifest.read_text().splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]
    if not entries or len(entries) != len(set(entries)):
        raise ValueError("Wire registry must contain unique package paths")
    expected = set()
    for entry in entries:
        directory = (root / entry).resolve()
        if not directory.is_relative_to(root) or not directory.is_dir():
            raise ValueError(f"invalid Wire package: {entry}")
        generated = directory / "wire_gen.go"
        if not generated.is_file():
            raise ValueError(f"missing generated Wire graph: {entry}")
        contents = generated.read_text()
        if "Code generated by Wire. DO NOT EDIT." not in contents:
            raise ValueError(f"missing Wire generated header: {entry}")
        if not any(line.startswith("//go:generate ") and "github.com/google/wire/cmd/wire" in line
                   for line in contents.splitlines()):
            raise ValueError(f"missing reproducible Wire generation directive: {entry}")
        expected.add(generated)
    actual = set()
    for module in modules:
        directory = (root / module).resolve()
        if not directory.is_relative_to(root) or not (directory / "go.mod").is_file():
            raise ValueError(f"missing or invalid module: {module}")
        actual.update(directory.rglob("wire_gen.go"))
    if actual != expected:
        missing = sorted(str(p.relative_to(root)) for p in actual - expected)
        extra = sorted(str(p.relative_to(root)) for p in expected - actual)
        raise ValueError(f"Wire registry mismatch: unregistered={missing}, outside modules={extra}")
    return entries


def check(root, manifest, modules, go):
    root = root.resolve()
    entries = registered_packages(root, manifest, modules)
    before = {entry: (root / entry / "wire_gen.go").read_bytes() for entry in entries}
    env = dict(os.environ, GOWORK="off")
    for entry in entries:
        print(f"==> Wire {entry}", flush=True)
        subprocess.run([go, "generate", "."], cwd=root / entry, env=env, check=True)
    registered_packages(root, manifest, modules)
    changed = False
    for entry, original in before.items():
        path = root / entry / "wire_gen.go"
        current = path.read_bytes()
        if current != original:
            changed = True
            sys.stderr.writelines(difflib.unified_diff(
                original.decode().splitlines(keepends=True),
                current.decode().splitlines(keepends=True),
                fromfile=f"before/{entry}/wire_gen.go",
                tofile=f"after/{entry}/wire_gen.go",
            ))
    if changed:
        raise ValueError("Wire generated code changed; review and commit regenerated graphs")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent.parent)
    parser.add_argument("--manifest", default="scripts/wire-packages.txt")
    parser.add_argument("--go", default="go")
    parser.add_argument("modules", nargs="+")
    args = parser.parse_args()
    try:
        check(args.root, args.root / args.manifest, args.modules, args.go)
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        print(f"wire-check: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
