import importlib.util
from pathlib import Path
import subprocess
import tempfile
import unittest
from unittest import mock


spec = importlib.util.spec_from_file_location("check_wire", Path(__file__).with_name("check-wire.py"))
check_wire = importlib.util.module_from_spec(spec)
spec.loader.exec_module(check_wire)


class WireGateTest(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name).resolve()
        self.package = self.root / "runtime/services/session/wire"
        self.package.mkdir(parents=True)
        (self.root / "runtime/go.mod").write_text("module example.com/runtime\n")
        self.injector = self.package / "providers.go"
        self.injector.write_text(
            "//go:build wireinject\n"
            "//go:generate go run -mod=mod github.com/google/wire/cmd/wire\n"
            "package wire\nfunc New() { wire.Build(Provider) }\n"
        )
        self.generated = self.package / "wire_gen.go"
        self.generated.write_text(
            "// Code generated by Wire. DO NOT EDIT.\n"
            "//go:build !wireinject\n"
            "package wire\n"
        )

    def test_inert_regeneration_passes_with_workspace_disabled(self):
        with mock.patch.object(check_wire.subprocess, "run") as run:
            check_wire.check(self.root, ["runtime"], "custom-go")
        run.assert_called_once()
        args, kwargs = run.call_args
        self.assertEqual(args[0], ["custom-go", "generate", "."])
        self.assertEqual(kwargs["cwd"], self.package)
        self.assertEqual(kwargs["env"]["GOWORK"], "off")
        self.assertTrue(kwargs["check"])

    def test_generated_drift_fails_and_keeps_reviewable_output(self):
        def regenerate(*args, **kwargs):
            self.generated.write_text(self.generated.read_text() + "// changed\n")
        with mock.patch.object(check_wire.subprocess, "run", side_effect=regenerate):
            with self.assertRaisesRegex(ValueError, "generated code changed"):
                check_wire.check(self.root, ["runtime"], "go")
        self.assertIn("changed", self.generated.read_text())

    def test_generator_failure_is_not_a_passing_check(self):
        failure = subprocess.CalledProcessError(2, ["go", "generate", "."])
        with mock.patch.object(check_wire.subprocess, "run", side_effect=failure):
            with self.assertRaises(subprocess.CalledProcessError):
                check_wire.check(self.root, ["runtime"], "go")

    def test_missing_module_is_not_silently_skipped(self):
        with self.assertRaisesRegex(ValueError, "missing or invalid module"):
            check_wire.discovered_packages(self.root, ["missing"])

    def test_unlisted_generated_package_is_discovered(self):
        extra = self.root / "runtime/services/tools/wire"
        extra.mkdir(parents=True)
        (extra / "wire.go").write_text(self.injector.read_text())
        (extra / "wire_gen.go").write_text(self.generated.read_text())
        self.assertEqual(
            check_wire.discovered_packages(self.root, ["runtime"]),
            ["runtime/services/session/wire", "runtime/services/tools/wire"],
        )

    def test_orphan_generated_graph_fails(self):
        self.injector.unlink()
        with self.assertRaisesRegex(ValueError, "orphan wire_gen.go"):
            check_wire.discovered_packages(self.root, ["runtime"])

    def test_orphan_injector_fails(self):
        self.generated.unlink()
        with self.assertRaisesRegex(ValueError, "orphan Wire injector"):
            check_wire.discovered_packages(self.root, ["runtime"])

    def test_malformed_injector_or_generated_graph_fails(self):
        mutations = [
            (self.injector, "generation directive", "//go:generate ", "// generate "),
            (self.injector, "wire.Build", "wire.Build(", "Build("),
            (self.generated, "generated header", "Code generated by Wire", "generated by something"),
            (self.generated, "build constraint", "//go:build !wireinject", "//go:build other"),
        ]
        for path, message, old, new in mutations:
            with self.subTest(message=message):
                original = path.read_text()
                path.write_text(original.replace(old, new))
                with self.assertRaisesRegex(ValueError, message):
                    check_wire.discovered_packages(self.root, ["runtime"])
                path.write_text(original)


if __name__ == "__main__":
    unittest.main()
