import importlib.util
from pathlib import Path
import subprocess
import tempfile
import unittest
from unittest import mock


spec = importlib.util.spec_from_file_location("check_wire", Path(__file__).with_name("check-wire.py"))
check_wire = importlib.util.module_from_spec(spec)
spec.loader.exec_module(check_wire)


class WireGateTest(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name).resolve()
        self.package = self.root / "runtime/services/session/wire"
        self.package.mkdir(parents=True)
        (self.root / "runtime/go.mod").write_text("module example.com/runtime\n")
        self.generated = self.package / "wire_gen.go"
        self.generated.write_text(
            "// Code generated by Wire. DO NOT EDIT.\n"
            "//go:generate go run -mod=mod github.com/google/wire/cmd/wire\n"
            "package wire\n"
        )
        self.manifest = self.root / "wire-packages.txt"
        self.manifest.write_text("runtime/services/session/wire\n")

    def test_inert_regeneration_passes_with_workspace_disabled(self):
        with mock.patch.object(check_wire.subprocess, "run") as run:
            check_wire.check(self.root, self.manifest, ["runtime"], "custom-go")
        run.assert_called_once()
        args, kwargs = run.call_args
        self.assertEqual(args[0], ["custom-go", "generate", "."])
        self.assertEqual(kwargs["cwd"], self.package)
        self.assertEqual(kwargs["env"]["GOWORK"], "off")
        self.assertTrue(kwargs["check"])

    def test_generated_drift_fails_and_keeps_reviewable_output(self):
        def regenerate(*args, **kwargs):
            self.generated.write_text(self.generated.read_text() + "// changed\n")
        with mock.patch.object(check_wire.subprocess, "run", side_effect=regenerate):
            with self.assertRaisesRegex(ValueError, "generated code changed"):
                check_wire.check(self.root, self.manifest, ["runtime"], "go")
        self.assertIn("changed", self.generated.read_text())

    def test_generator_failure_is_not_a_passing_check(self):
        failure = subprocess.CalledProcessError(2, ["go", "generate", "."])
        with mock.patch.object(check_wire.subprocess, "run", side_effect=failure):
            with self.assertRaises(subprocess.CalledProcessError):
                check_wire.check(self.root, self.manifest, ["runtime"], "go")

    def test_missing_module_is_not_silently_skipped(self):
        with self.assertRaisesRegex(ValueError, "missing or invalid module"):
            check_wire.registered_packages(self.root, self.manifest, ["missing"])

    def test_unregistered_injector_fails(self):
        extra = self.root / "runtime/wire"
        extra.mkdir()
        (extra / "wire_gen.go").write_text(self.generated.read_text())
        with self.assertRaisesRegex(ValueError, "unregistered"):
            check_wire.registered_packages(self.root, self.manifest, ["runtime"])

    def test_missing_generation_directive_fails(self):
        self.generated.write_text("// Code generated by Wire. DO NOT EDIT.\npackage wire\n")
        with self.assertRaisesRegex(ValueError, "generation directive"):
            check_wire.registered_packages(self.root, self.manifest, ["runtime"])

    def test_empty_or_duplicate_registry_fails(self):
        for content in ["# empty\n", self.manifest.read_text() * 2]:
            with self.subTest(content=content):
                self.manifest.write_text(content)
                with self.assertRaisesRegex(ValueError, "unique package paths"):
                    check_wire.registered_packages(self.root, self.manifest, ["runtime"])


if __name__ == "__main__":
    unittest.main()
