// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/duration"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/duration/internal/lifecycle"
	"github.com/portpowered/go-agent-harness/go-audio/pkg/clock"
)

// Injectors from providers.go:

func NewService(source clock.Source) duration.Service {
	v := durationClock(source)
	service := lifecycle.New(v)
	return service
}

func NewServiceWithClock(source duration.Clock) duration.Service {
	service := lifecycle.New(source)
	return service
}

// providers.go:

func durationClock(source clock.Source) duration.Clock {
	if candidate, ok := source.(duration.Clock); ok {
		return candidate
	}
	return nil
}
