package agentsession

// Diagnostic event names and field keys form the presentation contract.
const (
	SessionDiagnosticEventFailure                          = "session_failure"
	SessionDiagnosticEventTerminal                         = "session_terminal"
	SessionDiagnosticEventTurn                             = "session_turn_completed"
	SessionDiagnosticEventToolCall                         = "session_tool_call_unexecutable"
	SessionDiagnosticEventMetrics                          = "session_metrics"
	SessionDiagnosticEventRoomBound                        = "room_bound_shutdown"
	SessionDiagnosticFieldUnresolvedToolResultCount        = "unresolved_tool_result_count"
	SessionDiagnosticFieldUnresolvedToolCallIDs            = "unresolved_tool_call_ids"
	SessionDiagnosticFieldPendingImageContinuationCount    = "pending_image_continuation_count"
	SessionDiagnosticFieldPendingImageContinuationIDs      = "pending_image_continuation_call_ids"
	SessionDiagnosticFieldPendingToolContinuationCount     = "pending_tool_continuation_count"
	SessionDiagnosticFieldPendingToolContinuationIDs       = "pending_tool_continuation_call_ids"
	SessionDiagnosticFieldScheduledInputCount              = "scheduled_input_count"
	SessionDiagnosticFieldDispatchedInputCount             = "dispatched_input_count"
	SessionDiagnosticFieldCompletedTurnCount               = "completed_turn_count"
	SessionDiagnosticFieldPendingContinuationStatuses      = "pending_continuation_statuses"
	SessionDiagnosticFieldPendingContinuationCodes         = "pending_continuation_codes"
	SessionDiagnosticFieldPendingContinuationDetails       = "pending_continuation_details"
	SessionDiagnosticFieldCancelledBy                      = "cancelled_by"
	SessionDiagnosticFieldCancelledScheduledInputCount     = "cancelled_scheduled_input_count"
	SessionDiagnosticFieldCancelledToolResultCount         = "cancelled_tool_result_count"
	SessionDiagnosticFieldCancelledToolResultCallIDs       = "cancelled_tool_result_call_ids"
	SessionDiagnosticFieldCancelledToolContinuationCount   = "cancelled_tool_continuation_count"
	SessionDiagnosticFieldCancelledToolContinuationCallIDs = "cancelled_tool_continuation_call_ids"
	SessionDiagnosticEventPlaybackOverflow                 = "session_playback_overflow"
	SessionDiagnosticFieldPlaybackDeviceID                 = "device_id"
	SessionDiagnosticFieldPlaybackSampleRate               = "sample_rate"
	SessionDiagnosticFieldPlaybackChannels                 = "channels"
	SessionDiagnosticFieldPlaybackLatencyTargetMillis      = "latency_target_ms"
	SessionDiagnosticFieldPlaybackCapacitySamples          = "capacity_samples"
	SessionDiagnosticFieldPlaybackQueuedSamples            = "queued_samples"
	SessionDiagnosticFieldPlaybackPeakQueuedSamples        = "peak_queued_samples"
	SessionDiagnosticFieldPlaybackDroppedSamples           = "dropped_samples"
	SessionDiagnosticFieldPlaybackOverflowEvents           = "overflow_events"
	SessionDiagnosticFieldPlaybackParticipantID            = "participant_id"
)
