// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/roomevidence"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/roomevidence/internal/service"
)

// Injectors from wire.go:

// NewServiceWithOptions composes a service with caller-selected options.
// Zero-valued fields keep the production defaults.
func NewServiceWithOptions(options roomevidence.ServiceOptions) roomevidence.Service {
	serviceService := service.New(options)
	return serviceService
}
