// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/tools"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/tools/internal/execution"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/tools/internal/policy"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/tools/internal/service"
)

// Injectors from wire.go:

// NewService creates the inert tools service. Tool resources are resolved per
// request by the returned service rather than during graph construction.
func NewService() tools.Service {
	factory := execution.New()
	serviceService := service.NewWithExecution(factory)
	return serviceService
}

// NewExecutionService exposes the optional controller capability through the
// same registered tools service graph.
func NewExecutionService() tools.ExecutionService {
	factory := execution.New()
	serviceService := service.NewWithExecution(factory)
	return serviceService
}

// NewInteractiveToolPolicy creates the reusable interactive-policy factory.
func NewInteractiveToolPolicy() tools.InteractiveToolPolicyFactory {
	factory := policy.New()
	return factory
}
