// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionterminal"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionterminal/internal/service"
)

// Injectors from wire.go:

// NewService assembles one stateless terminal policy service.
func NewService() sessionterminal.Service {
	serviceService := service.New()
	return serviceService
}
