// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-loop/pkg/messages"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionturns"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionturns/internal/service"
)

// Injectors from wire.go:

// NewService constructs an inert service. It does not connect a provider.
func NewService(deps Dependencies) sessionturns.Service {
	service := newService(deps)
	return service
}

// wire.go:

// Dependencies are the explicit host-neutral edges used to construct one
// isolated session-turn service.
type Dependencies struct {
	SessionInferencer messages.SessionInferencer
	EventSink         sessionturns.TurnEventSink
}

func newService(deps Dependencies) *service.Service {
	return service.New(service.Dependencies{
		SessionInferencer: deps.SessionInferencer,
		EventSink:         deps.EventSink,
	})
}
