// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/recording"
	recordingservice "github.com/portpowered/go-agent-harness/go-agent-runtime/services/recording/internal/service"
	sessionservice "github.com/portpowered/go-agent-harness/go-agent-runtime/services/recording/internal/session"
	"github.com/portpowered/go-agent-harness/go-audio/pkg/clock"
)

// NewSessionService is the dedicated constructor for the runtime recording
// session façade. This generated constructor deliberately composes the
// existing recording service instead of changing the generic provider graph.
func NewSessionService(source clock.Source) recording.SessionService {
	capture := recordingservice.New(source)
	return sessionservice.New(capture, source)
}
