// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/recording"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/recording/internal/service"
	"github.com/portpowered/go-agent-harness/go-audio/pkg/clock"
)

// Injectors from providers.go:

func NewService(source clock.Source) recording.Service {
	serviceService := service.New(source)
	return serviceService
}
