// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/textseed"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/textseed/internal/service"
)

// Injectors from providers.go:

// NewService constructs a service with an explicit allocator. Passing nil
// selects the constructor-local production allocator.
func NewService(allocator textseed.Allocator) textseed.Service {
	serviceService := service.New(allocator)
	return serviceService
}

// NewDefaultService constructs a service with a fresh service-owned allocator.
func NewDefaultService() textseed.Service {
	serviceService := service.NewDefault()
	return serviceService
}
