// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/roomaudiodiagnostics"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/roomaudiodiagnostics/internal/service"
)

// Injectors from providers.go:

// NewService constructs one isolated participant ledger.
func NewService(options roomaudiodiagnostics.Options) roomaudiodiagnostics.Service {
	serviceService := service.New(options)
	return serviceService
}
