// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/roommedia"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/roommedia/internal/service"
)

// Injectors from providers.go:

func NewService(dependencies Dependencies) roommedia.Service {
	service := newService(dependencies)
	return service
}

// providers.go:

// Dependencies contains only the host's explicit timing source.
type Dependencies struct {
	Clock roommedia.Clock
}

func newService(dependencies Dependencies) *service.Service {
	return service.New(service.Dependencies{Clock: dependencies.Clock})
}
