#!/usr/bin/env python3
"""Generate the dedicated provider terminal-policy Wire artifact."""

from __future__ import annotations

import os
from pathlib import Path
import shutil
import subprocess
import tempfile


HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[4]
WIRE_DIR = REPO_ROOT / "go-agent-runtime/services/providers/wire"
SOURCE = WIRE_DIR / "terminal_policy.go"
TARGET = WIRE_DIR / "terminal_policy_gen.go"
WIRE_GENERATOR = [
    "go",
    "run",
    "-mod=mod",
    "github.com/google/wire/cmd/wire",
    "gen",
    "-tags",
    "terminalpolicywire",
    "-output_file_prefix",
    "terminal_policy_",
    ".",
]
GENERATED_HEADER = "// Code generated by Wire. DO NOT EDIT."


def main() -> int:
    source_lines = SOURCE.read_text(encoding="utf-8").splitlines()
    directives = [line for line in source_lines if line.startswith("//go:generate ")]
    if len(directives) != 1:
        raise RuntimeError(f"expected one source generation directive, got {len(directives)}")

    environment = dict(os.environ)
    environment["GOWORK"] = "off"
    with tempfile.TemporaryDirectory(prefix=".terminal-policy-wire.", dir=WIRE_DIR) as directory:
        temporary = Path(directory)
        shutil.copy2(SOURCE, temporary / "terminal_policy.go")
        subprocess.run(WIRE_GENERATOR, cwd=temporary, env=environment, check=True, timeout=120)
        generated_path = temporary / "terminal_policy_wire_gen.go"
        generated_lines = generated_path.read_text(encoding="utf-8").splitlines()

    if not generated_lines or generated_lines[0] != GENERATED_HEADER:
        raise RuntimeError("Wire output did not include the standard generated header")
    replaced = False
    output: list[str] = []
    for line in generated_lines:
        if line.startswith("//go:generate ") and not replaced:
            output.append(directives[0])
            replaced = True
        else:
            output.append(line)
    if not replaced:
        raise RuntimeError("Wire output did not contain its generation directive")
    TARGET.write_text("\n".join(output) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
