// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/captureclaim"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/captureclaim/internal/service"
)

// Injectors from providers.go:

// NewService constructs an inert capture-claim service from explicit seams.
func NewService(deps Dependencies) captureclaim.Service {
	serviceService := service.New(deps)
	return serviceService
}
