// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/providersession"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/providersession/internal/service"
)

type Dependencies = providersession.Dependencies

func NewService(deps Dependencies) providersession.Service { return service.New(deps) }
