// Code generated by the C52 evidence runner. It is copied into clean scratch
// archives only and is never part of a production or tracked test package.
package lifecycle

import (
	"encoding/json"
	"fmt"
	"os"
	"runtime"
	"sort"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/rooms"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/session"
)

var (
	c52TraceStart = time.Now()
	c52TraceMu    sync.Mutex
	c52TraceSeq   uint64
)

func c52Trace(kind, participant string, fields map[string]string) {
	path := strings.TrimSpace(os.Getenv("C52_TRACE_PATH"))
	if path == "" {
		return
	}
	sequence := atomic.AddUint64(&c52TraceSeq, 1)
	record := map[string]any{
		"schema":        "audio-runtime-c52-trace-v1",
		"seq":           sequence,
		"monotonic_ns":  time.Since(c52TraceStart).Nanoseconds(),
		"timestamp":     time.Now().UTC().Format(time.RFC3339Nano),
		"kind":          kind,
		"participant":   participant,
		"revision":      os.Getenv("C52_REVISION"),
		"matrix_cell":   os.Getenv("C52_MATRIX_CELL"),
		"goroutine_id":  c52GoroutineID(),
		"goroutine_count": runtime.NumGoroutine(),
	}
	if fields != nil {
		record["fields"] = fields
	}
	line, err := json.Marshal(record)
	if err != nil {
		fmt.Fprintf(os.Stderr, "c52 overlay trace marshal failed: %v\n", err)
		return
	}
	c52TraceMu.Lock()
	defer c52TraceMu.Unlock()
	file, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o600)
	if err != nil {
		fmt.Fprintf(os.Stderr, "c52 overlay trace open failed: %v\n", err)
		return
	}
	if _, err := file.Write(append(line, '\n')); err != nil {
		fmt.Fprintf(os.Stderr, "c52 overlay trace write failed: %v\n", err)
	}
	if err := file.Close(); err != nil {
		fmt.Fprintf(os.Stderr, "c52 overlay trace close failed: %v\n", err)
	}
}

func c52GoroutineID() string {
	var stack [96]byte
	n := runtime.Stack(stack[:], false)
	parts := strings.Fields(string(stack[:n]))
	if len(parts) > 1 && parts[0] == "goroutine" {
		return parts[1]
	}
	return ""
}

func c52TraceEvent(kind, participant string, event session.LiveEvent) {
	fields := map[string]string{
		"event_kind": event.Kind,
	}
	if event.SessionID != "" {
		fields["session_id"] = event.SessionID
	}
	if event.Text != "" {
		fields["text"] = event.Text
	}
	if event.Error != nil {
		fields["error"] = event.Error.Error()
	}
	if event.Liveness != nil {
		fields["liveness_classification"] = event.Liveness.Classification
		fields["response_id"] = event.Liveness.ResponseID
		fields["liveness_terminal_reason"] = string(event.Liveness.TerminalReason)
		fields["liveness_terminal_provenance"] = string(event.Liveness.TerminalProvenance)
		fields["liveness_output_state"] = string(event.Liveness.OutputState)
	}
	if event.Terminal != nil {
		fields["terminal_classification"] = event.Terminal.Classification
		fields["terminal_reason"] = string(event.Terminal.TerminalReason)
		fields["terminal_provenance"] = string(event.Terminal.TerminalProvenance)
		fields["terminal_output_state"] = string(event.Terminal.OutputState)
	}
	c52Trace(kind, participant, fields)
}

func c52TraceDiagnostic(participant string, record rooms.RoomDiagnosticRecord) {
	fields := map[string]string{
		"event": record.Event,
	}
	for key, value := range record.Fields {
		fields["field_"+key] = value
	}
	c52Trace("diagnostic_published", participant, fields)
}

func c52TraceRoomResult(kind string, result rooms.RoomResult, runErr error) {
	fields := map[string]string{
		"termination_reason": string(result.TerminationReason),
		"reason":             string(result.Reason),
		"result_error":       result.Error,
		"run_error":          c52ErrorString(runErr),
	}
	ids := make([]string, 0, len(result.Participants))
	for id := range result.Participants {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	participants := make(map[string]rooms.RoomParticipantResult, len(ids))
	for _, id := range ids {
		participants[id] = result.Participants[id]
	}
	if encoded, err := json.Marshal(participants); err == nil {
		fields["participants_json"] = string(encoded)
	}
	c52Trace(kind, "room", fields)
}

func c52ErrorString(err error) string {
	if err == nil {
		return ""
	}
	return err.Error()
}

func c52Int(value int) string {
	return strconv.Itoa(value)
}

func c52Bool(value bool) string {
	return strconv.FormatBool(value)
}

func c52CancelKind(err error) string {
	if err == nil {
		return "nil"
	}
	message := strings.ToLower(err.Error())
	if message == "context canceled" || message == "context cancelled" {
		return "context_cancellation"
	}
	if strings.Contains(message, "silent_provider_") {
		return "typed_liveness"
	}
	return "other"
}

func c52ShouldSwapCases() bool {
	switch strings.ToLower(strings.TrimSpace(os.Getenv("C52_CASE_ORDER"))) {
	case "timeout-first":
		return true
	case "empty-first":
		return false
	}
	seed, err := strconv.ParseInt(strings.TrimSpace(os.Getenv("C52_SHUFFLE_SEED")), 10, 64)
	return err == nil && seed%2 != 0
}
