// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/livedelegation"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/livedelegation/internal/service"
)

// Injectors from wire.go:

// NewService assembles the live delegation executor service behind its
// public contract.
func NewService(deps Dependencies) livedelegation.Service {
	providersService := deps.Providers
	credentialResolver := deps.Credentials
	scheduler := deps.Scheduler
	serviceService := service.New(providersService, credentialResolver, scheduler)
	return serviceService
}
