// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/rtcsession"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/rtcsession/internal/service"
	"github.com/portpowered/go-agent-harness/go-audio/pkg/observability"
)

// Injectors from providers.go:

// NewService creates an inert RTC lifecycle service. Endpoint resolution,
// data-plane creation, and media opening begin only when a runtime starts.
func NewService(components rtcsession.SessionRTCComponents, sampler observability.MetricSampler, logger observability.Logger) rtcsession.Service {
	serviceService := service.New(components, sampler, logger)
	return serviceService
}
