// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/terminaloutcome"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/terminaloutcome/internal/service"
)

// Injectors from providers.go:

// NewService assembles one host-neutral terminal-outcome service.
func NewService() terminaloutcome.Service {
	serviceService := service.New()
	return serviceService
}
