// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionobservation"
	"github.com/portpowered/go-agent-harness/go-agent-runtime/services/sessionobservation/internal/service"
	"github.com/portpowered/go-agent-harness/go-audio/pkg/clock"
)

// Injectors from providers.go:

// NewService creates an isolated recorder with the supplied observer and
// clock. No provider, CLI, credential, or process-global dependency is read.
func NewService(observer sessionobservation.SessionRuntimeObserver, source clock.Source) sessionobservation.Service {
	serviceService := service.New(observer, source)
	return serviceService
}
